// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AgentDto = {
    id?: string;
    projectId?: string;
    agentRoleId?: string;
    roleName?: null | string;
    status?: null | string;
    currentTask?: null | string;
    agentRole?: null | AgentRoleSummaryDto;
};

export type AgentEventDto = {
    id?: string;
    eventType?: null | string;
    data?: null | string;
    content?: null | string;
    metadata?: null | string;
    taskId?: null | string;
    sessionId?: null | string;
    frameId?: null | string;
    messageId?: null | string;
    executionPackageId?: null | string;
    scene?: null | string;
    entryKind?: null | string;
    agentRoleId?: null | string;
    projectAgentRoleId?: null | string;
    targetAgentRoleId?: null | string;
    targetProjectAgentRoleId?: null | string;
    model?: null | string;
    toolName?: null | string;
    toolCallId?: null | string;
    status?: null | string;
    sourceFrameId?: null | string;
    sourceEffectIndex?: null | number | string;
    detail?: null | string;
    attempt?: null | number | string;
    maxAttempts?: null | number | string;
    totalTokens?: null | number | string;
    durationMs?: null | number | string;
    firstTokenMs?: null | number | string;
    createdAt?: string;
};

export type AgentRoleDto = {
    id?: string;
    name?: string;
    roleType?: string;
    description?: null | string;
    jobTitle?: null | string;
    systemPrompt?: null | string;
    avatar?: null | string;
    isBuiltin?: boolean;
    isVirtual?: boolean;
    source?: AgentSource;
    providerType?: null | string;
    modelProviderId?: null | string;
    modelProviderName?: null | string;
    modelName?: null | string;
    config?: null | string;
    soul?: null | AgentSoulDto;
    createdAt?: string;
};

export type AgentRoleInput = {
    name?: null | string;
    description?: null | string;
    modelName?: null | string;
    modelProviderId?: null | string;
    temperature?: null | number | string;
    soul?: null | AgentSoulDto;
};

export type AgentRoleMcpBindingDto = {
    id?: string;
    agentRoleId?: string;
    mcpServerId?: string;
    mcpServerName?: string;
    icon?: null | string;
    mode?: string;
    transportType?: string;
    toolFilter?: null | string;
    selectedProfileId?: null | string;
    parameterValues?: null | string;
    isEnabled?: boolean;
};

export type AgentRoleMcpBindingInput = {
    mcpServerId?: string;
    toolFilter?: null | string;
    selectedProfileId?: null | string;
    parameterValues?: null | string;
    isEnabled?: boolean;
};

export type AgentRoleSkillBindingDto = {
    id?: string;
    agentRoleId?: string;
    skillInstallKey?: string;
    skillId?: string;
    name?: string;
    displayName?: string;
    source?: string;
    owner?: string;
    repo?: string;
    githubUrl?: null | string;
    isEnabled?: boolean;
    resolutionStatus?: string;
    resolutionMessage?: null | string;
    installRootPath?: null | string;
    createdAt?: string;
    updatedAt?: string;
};

export type AgentRoleSkillBindingInput = {
    skillInstallKey?: string;
    skillId?: string;
    name?: string;
    displayName?: string;
    source?: string;
    owner?: string;
    repo?: string;
    githubUrl?: null | string;
    isEnabled?: boolean;
};

export type AgentRoleSummaryDto = {
    id?: string;
    name?: string;
    description?: null | string;
};

export type AgentRoleTemplateMcpRequirementDto = {
    key?: null | string;
    name?: null | string;
    npmPackage?: null | string;
    pypiPackage?: null | string;
    status?: string;
    matchStrategy?: null | string;
    message?: null | string;
    matchedServerId?: null | string;
    matchedServerName?: null | string;
    matchedServerSource?: null | string;
    configCount?: number | string;
};

export type AgentRoleTemplatePreviewDto = {
    externalId?: null | string;
    name?: string;
    jobTitle?: null | string;
    description?: null | string;
    avatar?: null | string;
    modelName?: null | string;
    modelConfig?: null | string;
    soul?: null | AgentSoulDto;
};

export type AgentRoleTemplateSkillRequirementDto = {
    key?: null | string;
    source?: null | string;
    sourceKey?: null | string;
    owner?: null | string;
    repo?: null | string;
    skillId?: string;
    status?: string;
    matchStrategy?: null | string;
    message?: null | string;
    installKey?: null | string;
    displayName?: null | string;
};

export type AgentRuntimeMissingSkillDto = {
    bindingScope?: string;
    skillInstallKey?: string;
    skillId?: string;
    displayName?: string;
    message?: string;
};

export type AgentRuntimePreviewDto = {
    projectId?: string;
    projectAgentRoleId?: string;
    agentRoleId?: string;
    roleName?: null | string;
    jobTitle?: null | string;
    prompt?: string;
    tools?: Array<AgentRuntimeToolDto>;
    skills?: Array<AgentRuntimeSkillDto>;
    missingSkills?: Array<AgentRuntimeMissingSkillDto>;
};

export type AgentRuntimeSkillDto = {
    installKey?: string;
    skillId?: string;
    displayName?: string;
    source?: string;
    directoryPath?: string;
};

export type AgentRuntimeToolDto = {
    name?: string;
    description?: null | string;
    source?: string;
};

export type AgentSoulCatalogDto = {
    traits?: Array<AgentSoulOptionDto>;
    attitudes?: Array<AgentSoulOptionDto>;
    styles?: Array<AgentSoulOptionDto>;
};

export type AgentSoulDto = {
    traits?: Array<string>;
    style?: null | string;
    attitudes?: Array<string>;
    custom?: null | string;
};

export type AgentSoulOptionDto = {
    key?: string;
    label?: string;
};

export type AgentSource = number;

export type ApiMessageDto = {
    message?: string;
};

export type ApiStatusDto = {
    status?: string;
};

export type BatchStatusRequest = {
    tasks?: Array<TaskStatusUpdateInput>;
};

export type ChatMessageDto = {
    id?: string;
    sessionId?: string;
    frameId?: string;
    executionPackageId?: null | string;
    originatingFrameId?: null | string;
    parentMessageId?: null | string;
    role?: null | string;
    agentRoleId?: null | string;
    projectAgentRoleId?: null | string;
    content?: null | string;
    contentType?: null | string;
    tokenUsage?: null | number | string;
    durationMs?: null | number | string;
    usage?: null | ChatMessageUsageDto;
    timing?: null | ChatMessageTimingDto;
    createdAt?: string;
};

export type ChatMessageListOutput = {
    messages?: Array<ChatMessageDto>;
    total?: number | string;
};

export type ChatMessageRequest = {
    input?: string;
    rawInput?: null | string;
    mentions?: null | Array<ConversationMentionDto>;
};

export type ChatMessageTimingDto = {
    totalMs?: null | number | string;
    firstTokenMs?: null | number | string;
};

export type ChatMessageUsageDto = {
    inputTokens?: null | number | string;
    outputTokens?: null | number | string;
    totalTokens?: null | number | string;
};

export type CheckpointDto = {
    id?: string;
    name?: null | string;
    description?: null | string;
    commitSha?: null | string;
    createdAt?: string;
};

export type ConfigurationProperty = {
    name?: string;
    type?: ConfigurationPropertyType;
    default_value?: unknown;
    required?: boolean;
};

export type ConfigurationPropertyType = number;

export type ContentDto = {
    content?: null | string;
};

export type ConversationMentionDto = {
    rawText?: string;
    resolvedKind?: null | string;
    builtinRole?: null | string;
    projectAgentRoleId?: null | string;
};

export type ConversationTaskOutput = {
    taskId?: string;
    status?: string;
    sessionId?: null | string;
    projectId?: null | string;
    scene?: null | string;
    entryKind?: null | string;
    projectAgentRoleId?: null | string;
    agentRoleId?: null | string;
    isAwaitingInput?: boolean;
};

export type CreateAgentRoleInput = {
    name?: string;
    roleType?: string;
    description?: null | string;
    jobTitle?: null | string;
    systemPrompt?: null | string;
    avatar?: null | string;
    source?: AgentSource;
    providerType?: null | string;
    modelProviderId?: null | string;
    modelName?: null | string;
    config?: null | string;
    soul?: null | AgentSoulDto;
};

export type CreateMcpBindingDraftInput = {
    mcpServerId?: string;
    scope?: string;
    projectAgentRoleId?: null | string;
    agentRoleId?: null | string;
};

export type CreateMcpServerConfigInput = {
    mcpServerId?: string;
    name?: string;
    description?: null | string;
    selectedProfileId?: null | string;
    parameterValues?: null | string;
};

export type CreateMcpServerInput = {
    name?: string;
    description?: null | string;
    icon?: null | string;
    category?: string;
    transportType?: string;
    mode?: string;
    templateJson?: null | string;
    homepage?: null | string;
    npmPackage?: null | string;
    pypiPackage?: null | string;
};

export type CreateProjectInput = {
    name?: string;
    description?: null | string;
    language?: null | string;
    defaultProviderId?: null | string;
    defaultModelName?: null | string;
};

export type CreateProviderAccountInput = {
    name?: string;
    protocolType?: string;
    isEnabled?: boolean;
};

export type CreateSessionInput = {
    projectId?: string;
    input?: string;
    rawInput?: null | string;
    contextStrategy?: null | string;
    scene?: null | string;
    mentions?: null | Array<ConversationMentionDto>;
};

export type CreateTaskInput = {
    title?: string;
    description?: null | string;
    priority?: number | string;
    parentTaskId?: null | string;
    assignedProjectAgentRoleId?: null | string;
    dependsOn?: null | Array<string>;
};

export type DeleteMcpServerResultDto = {
    serverId?: string;
    installId?: null | string;
    deleted?: boolean;
    uninstalled?: boolean;
    action?: string;
    message?: null | string;
    blockingReasons?: Array<string>;
    referencedByConfigs?: Array<string>;
    referencedByProjectBindings?: Array<string>;
    referencedByRoleBindings?: Array<string>;
};

export type DeviceAuthPollDto = {
    status?: string;
    message?: string;
    interval?: null | number | string;
};

export type DeviceCodeDto = {
    userCode?: string;
    verificationUri?: string;
    expiresIn?: number | string;
    interval?: number | string;
};

export type DiffDto = {
    diff?: null | string;
};

export type EventDto = {
    id?: string;
    eventType?: null | string;
    data?: null | string;
    content?: null | string;
    metadata?: null | string;
    taskId?: null | string;
    sessionId?: null | string;
    frameId?: null | string;
    messageId?: null | string;
    executionPackageId?: null | string;
    projectAgentRoleId?: null | string;
    agentName?: null | string;
    scene?: null | string;
    entryKind?: null | string;
    agentRoleId?: null | string;
    targetAgentRoleId?: null | string;
    targetProjectAgentRoleId?: null | string;
    model?: null | string;
    toolName?: null | string;
    toolCallId?: null | string;
    status?: null | string;
    sourceFrameId?: null | string;
    sourceEffectIndex?: null | number | string;
    detail?: null | string;
    attempt?: null | number | string;
    maxAttempts?: null | number | string;
    totalTokens?: null | number | string;
    durationMs?: null | number | string;
    firstTokenMs?: null | number | string;
    createdAt?: string;
};

export type FileNodeDto = {
    name?: string;
    path?: string;
    isDirectory?: boolean;
    children?: null | Array<FileNodeDto>;
};

export type GetConfigurationResultOfJsonElement = {
    properties?: Array<ConfigurationProperty>;
    configuration?: JsonElement;
};

export type HealthStatusDto = {
    status?: string;
    timestamp?: string;
    version?: string;
};

export type HireTalentMarketRoleInput = {
    sourceKey?: string;
    templateId?: string;
    overwriteExisting?: boolean;
};

export type IFormFile = Blob | File;

export type ImportAgentRoleTemplateInput = {
    content?: string;
    overwriteExisting?: boolean;
};

export type ImportAgentRoleTemplateResultDto = {
    role?: AgentRoleDto;
    preview?: PreviewAgentRoleTemplateImportResultDto;
    addedMcpBindings?: number | string;
    addedSkillBindings?: number | string;
};

export type InstalledSkillDto = {
    id?: string;
    installKey?: string;
    sourceKey?: string;
    scope?: string;
    projectId?: null | string;
    projectName?: null | string;
    source?: string;
    owner?: string;
    repo?: string;
    skillId?: string;
    name?: string;
    displayName?: string;
    description?: null | string;
    githubUrl?: null | string;
    installs?: number | string;
    installMode?: string;
    targetAgents?: Array<string>;
    installRootPath?: string;
    isEnabled?: boolean;
    status?: string;
    statusMessage?: null | string;
    isManaged?: boolean;
    sourceRevision?: null | string;
    createdAt?: string;
    updatedAt?: string;
};

export type InstallFromMarketplaceInput = {
    sourceKey?: string;
    serverId?: string;
    name?: null | string;
};

export type InstallMcpServerInput = {
    sourceKey?: string;
    catalogEntryId?: string;
    selectedChannelId?: null | string;
    requestedVersion?: null | string;
    name?: null | string;
    overwriteExisting?: boolean;
};

export type InstallSkillInput = {
    sourceKey?: string;
    owner?: string;
    repo?: string;
    skillId?: string;
    overwriteExisting?: boolean;
};

export type JsonElement = unknown;

export type MarketplaceSearchResultDto = {
    items?: Array<MarketplaceServerDto>;
    totalCount?: number | string;
    nextCursor?: null | string;
};

export type MarketplaceServerDto = {
    id?: string;
    name?: string;
    description?: null | string;
    icon?: null | string;
    category?: string;
    transportTypes?: Array<string>;
    source?: string;
    version?: null | string;
    repositoryUrl?: null | string;
    homepage?: null | string;
    npmPackage?: null | string;
    pypiPackage?: null | string;
    defaultConfig?: null | string;
    isInstalled?: boolean;
};

export type MarketplaceSourceDto = {
    sourceKey?: string;
    displayName?: string;
    iconUrl?: null | string;
};

export type McpBindingDraftDto = {
    mcpServerId?: string;
    toolFilter?: null | string;
    selectedProfileId?: null | string;
    parameterValues?: null | string;
    isEnabled?: boolean;
};

export type McpCatalogEntryDto = {
    entryId?: string;
    sourceKey?: string;
    name?: string;
    displayName?: string;
    description?: null | string;
    category?: null | string;
    version?: null | string;
    homepage?: null | string;
    repositoryUrl?: null | string;
    transportTypes?: Array<string>;
    installChannels?: Array<McpInstallChannelDto>;
    isInstalled?: boolean;
    installedState?: null | string;
    installedVersion?: null | string;
    installId?: null | string;
};

export type McpCatalogSearchResultDto = {
    items?: Array<McpCatalogEntryDto>;
    totalCount?: number | string;
    nextCursor?: null | string;
};

export type McpInstallChannelDto = {
    channelId?: string;
    channelType?: string;
    transportType?: string;
    version?: null | string;
    entrypointHint?: null | string;
    packageIdentifier?: null | string;
    artifactUrl?: null | string;
    metadata?: {
        [key: string]: string;
    };
};

export type McpLaunchProfileDto = {
    id?: string;
    displayName?: null | string;
    profileType?: string;
    transportType?: string;
    runnerKind?: null | string;
    runner?: null | string;
    ecosystem?: null | string;
    packageName?: null | string;
    packageVersion?: null | string;
    image?: null | string;
    imageTagTemplate?: null | string;
    command?: null | string;
    commandTemplate?: null | string;
    workingDirectoryTemplate?: null | string;
    urlTemplate?: null | string;
    argsTemplate?: Array<string>;
    envTemplate?: {
        [key: string]: string;
    };
    headersTemplate?: {
        [key: string]: string;
    };
};

export type McpParameterSchemaItemDto = {
    key?: string;
    label?: null | string;
    type?: string;
    required?: boolean;
    defaultValue?: unknown;
    defaultValueSource?: null | string;
    projectOverrideValueSource?: null | string;
    description?: null | string;
    appliesToProfiles?: Array<string>;
};

export type McpRepairResultDto = {
    repaired?: boolean;
    message?: null | string;
    server?: McpServerDto;
};

export type McpServerConfigDto = {
    id?: string;
    mcpServerId?: string;
    mcpServerName?: string;
    name?: string;
    description?: null | string;
    transportType?: string;
    selectedProfileId?: null | string;
    parameterValues?: null | string;
    hasEnvironmentVariables?: boolean;
    hasAuthConfig?: boolean;
    isEnabled?: boolean;
    createdAt?: string;
};

export type McpServerDto = {
    id?: string;
    name?: string;
    description?: null | string;
    icon?: null | string;
    logo?: null | string;
    category?: string;
    transportType?: string;
    mode?: string;
    source?: string;
    templateJson?: null | string;
    installId?: null | string;
    catalogEntryId?: null | string;
    installSourceKey?: null | string;
    installChannelId?: null | string;
    installChannelType?: null | string;
    installedVersion?: null | string;
    installedState?: null | string;
    installDirectory?: null | string;
    manifestPath?: null | string;
    lastInstallError?: null | string;
    isManagedInstall?: boolean;
    homepage?: null | string;
    npmPackage?: null | string;
    pypiPackage?: null | string;
    isEnabled?: boolean;
    configCount?: number | string;
    defaultProfileId?: null | string;
    profiles?: Array<McpLaunchProfileDto>;
    parameterSchema?: Array<McpParameterSchemaItemDto>;
};

export type McpSourceDto = {
    sourceKey?: string;
    displayName?: string;
};

export type McpToolDto = {
    name?: string;
    description?: null | string;
    inputSchema?: null | string;
};

export type McpUninstallCheckResultDto = {
    canUninstall?: boolean;
    blockingReasons?: Array<string>;
    referencedByConfigs?: Array<string>;
    referencedByProjectBindings?: Array<string>;
    referencedByRoleBindings?: Array<string>;
};

export type ModelDataDto = {
    id?: string;
    name?: string;
    description?: null | string;
    reasoning?: boolean;
    toolCall?: boolean;
    attachment?: boolean;
    contextWindow?: null | number | string;
    maxOutput?: null | number | string;
    inputPrice?: null | number | string;
    outputPrice?: null | number | string;
    inputModalities?: null | string;
    outputModalities?: null | string;
};

export type ModelDataProviderDto = {
    key?: string;
    name?: string;
    modelCount?: number | string;
};

export type ModelDataStatusDto = {
    isReady?: boolean;
    lastUpdatedUtc?: null | string;
    sourceId?: null | string;
    vendorCount?: number | string;
};

export type PagedAgentEventsDto = {
    items?: Array<AgentEventDto>;
    total?: number | string;
};

export type PagedResultOfEventDto = {
    items?: Array<EventDto>;
    total?: number | string;
};

export type PagedResultOfProviderAccountDto = {
    items?: Array<ProviderAccountDto>;
    total?: number | string;
};

export type PermissionAuthorizationSubmitResult = {
    requestId: string;
    status: string;
    accepted: boolean;
};

export type PermissionListenerLease = {
    listenerId: string;
    expiresAt: string;
    pendingRequests?: null | Array<PermissionRequestNotification>;
};

export type PermissionListenerRegistrationBody = {
    listenerId?: null | string;
};

export type PermissionRequestNotification = {
    requestId: string;
    kind: string;
    message: string;
    sessionId?: null | string;
    projectId?: null | string;
    agentInstanceId?: null | string;
    projectAgentRoleId?: null | string;
    copilotSessionId?: null | string;
    roleName?: null | string;
    projectName?: null | string;
    scene?: null | string;
    dispatchSource?: null | string;
    toolCallId?: null | string;
    toolName?: null | string;
    fileName?: null | string;
    url?: null | string;
    commandText?: null | string;
    warning?: null | string;
    detailsJson?: null | string;
    createdAt?: string;
    timeoutMs?: number | string;
};

export type PermissionRequestResponseBody = {
    listenerId?: string;
    kind?: string;
};

export type PreviewAgentRoleTemplateImportInput = {
    content?: string;
};

export type PreviewAgentRoleTemplateImportResultDto = {
    role?: AgentRoleTemplatePreviewDto;
    mcps?: Array<AgentRoleTemplateMcpRequirementDto>;
    skills?: Array<AgentRoleTemplateSkillRequirementDto>;
};

export type PreviewTalentMarketHireInput = {
    sourceKey?: string;
    templateId?: string;
};

export type ProjectAgentDto = {
    id?: string;
    roleName?: null | string;
    status?: null | string;
};

export type ProjectAgentMcpBindingDto = {
    id?: string;
    projectAgentRoleId?: string;
    mcpServerId?: string;
    mcpServerName?: string;
    icon?: null | string;
    mode?: string;
    transportType?: string;
    toolFilter?: null | string;
    selectedProfileId?: null | string;
    parameterValues?: null | string;
    isEnabled?: boolean;
};

export type ProjectAgentMcpBindingInput = {
    mcpServerId?: string;
    toolFilter?: null | string;
    selectedProfileId?: null | string;
    parameterValues?: null | string;
    isEnabled?: boolean;
};

export type ProjectDto = {
    id?: string;
    name?: string;
    description?: null | string;
    workspacePath?: null | string;
    status?: string;
    phase?: string;
    language?: string;
    defaultProviderId?: null | string;
    defaultModelName?: null | string;
    extraConfig?: null | string;
    createdAt?: string;
    updatedAt?: string;
};

export type ProjectStatsDto = {
    agents?: Array<ProjectAgentDto>;
    tasksByStatus?: {
        [key: string]: number | string;
    };
    eventsByType?: {
        [key: string]: number | string;
    };
    sceneBreakdown?: Array<SceneBreakdownDto>;
    recentEvents?: Array<EventDto>;
    checkpoints?: number | string;
};

export type ProtocolEnvField = {
    name: string;
    fieldType: string;
    defaultValue: string;
};

export type ProtocolMetadata = {
    providerKey: string;
    providerName: string;
    logo: string;
    isVendor: boolean;
    protocolClassName: string;
    envSchema: Array<ProtocolEnvField>;
};

export type ProviderAccountDto = {
    id?: string;
    name?: string;
    protocolType?: string;
    isEnabled?: boolean;
    createdAt?: string;
    updatedAt?: null | string;
};

export type ProviderInfo = {
    key?: string;
    displayName?: string;
    description?: string;
    logo?: null | string;
};

export type ProviderModelDto = {
    id?: string;
    vendor?: string;
    protocols?: string;
};

export type RecentSessionDto = {
    id?: string;
    projectId?: string;
    projectName?: null | string;
    status?: null | string;
    scene?: null | string;
    input?: null | string;
    createdAt?: string;
};

export type SceneBreakdownDto = {
    scene?: string;
    sessionCount?: number | string;
    taskCount?: number | string;
    eventCount?: number | string;
    runCount?: number | string;
    totalTokens?: number | string;
    averageDurationMs?: null | number | string;
};

export type SendMessageBody = {
    message?: string;
};

export type SessionDto = {
    id?: string;
    projectId?: string;
    status?: null | string;
    scene?: null | string;
    input?: null | string;
    result?: null | string;
    contextStrategy?: null | string;
    createdAt?: string;
    completedAt?: null | string;
    isActive?: boolean;
    frames?: null | Array<SessionFrameDto>;
};

export type SessionEventDto = {
    id?: string;
    sessionId?: string;
    frameId?: null | string;
    messageId?: null | string;
    executionPackageId?: null | string;
    sourceFrameId?: null | string;
    sourceEffectIndex?: null | number | string;
    eventType?: null | string;
    payload?: null | string;
    sequenceNo?: number | string;
    createdAt?: string;
};

export type SessionFrameDto = {
    id?: string;
    parentFrameId?: null | string;
    taskId?: null | string;
    executionPackageId?: null | string;
    entryMessageId?: null | string;
    parentMessageId?: null | string;
    agentRoleId?: null | string;
    projectAgentRoleId?: null | string;
    targetAgentRoleId?: null | string;
    targetProjectAgentRoleId?: null | string;
    initiatorAgentRoleId?: null | string;
    initiatorProjectAgentRoleId?: null | string;
    purpose?: null | string;
    status?: null | string;
    result?: null | string;
    depth?: number | string;
    order?: number | string;
    createdAt?: string;
    completedAt?: null | string;
};

export type SetAgentsBody = {
    agentRoleIds?: Array<string>;
};

export type SkillCatalogItemDto = {
    sourceKey?: string;
    source?: string;
    skillId?: string;
    name?: string;
    displayName?: string;
    description?: null | string;
    installs?: number | string;
    owner?: string;
    repo?: string;
    githubUrl?: null | string;
    isInstalled?: boolean;
};

export type SkillCatalogPageDto = {
    items?: Array<SkillCatalogItemDto>;
    total?: number | string;
    page?: number | string;
    pageSize?: number | string;
    totalPages?: number | string;
    scrapedAt?: null | string;
};

export type SkillCatalogSourceDto = {
    sourceKey?: string;
    displayName?: string;
    source?: string;
    owner?: string;
    repo?: string;
    skillCount?: number | string;
    totalInstalls?: number | string;
};

export type SystemSettingsDto = {
    teamName?: string;
    teamDescription?: string;
    userName?: string;
    language?: string;
    timezone?: string;
    defaultTemperature?: number | string;
    defaultMaxTokens?: number | string;
    responseStyle?: string;
    autoApproveProjectGroupCapabilities?: boolean;
};

export type SystemStatsDto = {
    projects?: number | string;
    agents?: number | string;
    tasks?: number | string;
    events?: number | string;
    completedTasks?: number | string;
    sessions?: number | string;
    modelProviders?: number | string;
    agentRoles?: number | string;
    recentSessions?: Array<RecentSessionDto>;
};

export type TalentMarketHirePreviewDto = {
    sourceKey?: string;
    template?: TalentMarketRoleSummaryDto;
    preview?: PreviewAgentRoleTemplateImportResultDto;
    matchedRoleId?: null | string;
    matchedRoleName?: null | string;
    canOverwrite?: boolean;
    requiresOverwriteConfirmation?: boolean;
    overwriteBlockedReason?: null | string;
};

export type TalentMarketRoleSummaryDto = {
    templateId?: string;
    sourceKey?: string;
    file?: null | string;
    name?: string;
    job?: null | string;
    jobTitle?: null | string;
    description?: null | string;
    modelName?: null | string;
    source?: null | string;
    isBuiltin?: boolean;
    isActive?: boolean;
    mcpCount?: number | string;
    skillCount?: number | string;
    isHired?: boolean;
    matchedRoleId?: null | string;
    matchedRoleName?: null | string;
    canOverwrite?: boolean;
};

export type TalentMarketSearchResultDto = {
    items?: Array<TalentMarketRoleSummaryDto>;
    totalCount?: number | string;
};

export type TalentMarketSourceDto = {
    sourceKey?: string;
    displayName?: string;
};

export type TaskDto = {
    id?: string;
    title?: string;
    description?: null | string;
    status?: string;
    priority?: number | string;
    assignedProjectAgentRoleId?: null | string;
    assignedAgentName?: null | string;
    assignedRoleName?: null | string;
    parentTaskId?: null | string;
    subTasks?: null | Array<TaskDto>;
    dependencies?: null | Array<string>;
    sessionId?: null | string;
    executionPackageId?: null | string;
    frameId?: null | string;
    messageId?: null | string;
    scene?: null | string;
    entryKind?: null | string;
    mentionedAgentRoleId?: null | string;
    mentionedProjectAgentRoleId?: null | string;
    dispatchSource?: null | string;
    targetAgentRoleId?: null | string;
    targetProjectAgentRoleId?: null | string;
    lastStatus?: null | string;
    sourceFrameId?: null | string;
    sourceEffectIndex?: null | number | string;
    lastResult?: null | string;
    lastError?: null | string;
    model?: null | string;
    attemptCount?: number | string;
    totalTokens?: null | number | string;
    durationMs?: null | number | string;
    firstTokenMs?: null | number | string;
    createdAt?: string;
    updatedAt?: string;
    completedAt?: null | string;
};

export type TaskStatusUpdateInput = {
    taskId?: string;
    status?: string;
};

export type TaskTimelineDto = {
    id?: string;
    eventType?: null | string;
    data?: null | string;
    content?: null | string;
    metadata?: null | string;
    taskId?: null | string;
    sessionId?: null | string;
    executionPackageId?: null | string;
    frameId?: null | string;
    messageId?: null | string;
    scene?: null | string;
    entryKind?: null | string;
    agentRoleId?: null | string;
    projectAgentRoleId?: null | string;
    targetAgentRoleId?: null | string;
    targetProjectAgentRoleId?: null | string;
    model?: null | string;
    toolName?: null | string;
    toolCallId?: null | string;
    status?: null | string;
    sourceFrameId?: null | string;
    sourceEffectIndex?: null | number | string;
    detail?: null | string;
    attempt?: null | number | string;
    maxAttempts?: null | number | string;
    totalTokens?: null | number | string;
    durationMs?: null | number | string;
    firstTokenMs?: null | number | string;
    createdAt?: string;
};

export type TestChatBody = {
    message?: string;
    override?: null | AgentRoleInput;
};

export type TestMcpConnectionDraftInput = {
    mcpServerId?: string;
    selectedProfileId?: null | string;
    parameterValues?: null | string;
};

export type TestMcpConnectionResult = {
    success?: boolean;
    message?: null | string;
    tools?: Array<McpToolDto>;
};

export type UninstallSkillInput = {
    owner?: string;
    repo?: string;
    skillId?: string;
};

export type UpdateAgentRoleInput = {
    name?: null | string;
    description?: null | string;
    jobTitle?: null | string;
    systemPrompt?: null | string;
    avatar?: null | string;
    modelProviderId?: null | string;
    modelName?: null | string;
    config?: null | string;
    soul?: null | AgentSoulDto;
};

export type UpdatedCountDto = {
    updated?: number | string;
};

export type UpdateMcpServerConfigInput = {
    name?: null | string;
    description?: null | string;
    selectedProfileId?: null | string;
    parameterValues?: null | string;
    isEnabled?: null | boolean;
};

export type UpdateMcpServerInput = {
    name?: null | string;
    description?: null | string;
    icon?: null | string;
    category?: null | string;
    transportType?: null | string;
    mode?: null | string;
    templateJson?: null | string;
    homepage?: null | string;
    npmPackage?: null | string;
    pypiPackage?: null | string;
    isEnabled?: null | boolean;
};

export type UpdateProjectInput = {
    name?: null | string;
    description?: null | string;
    language?: null | string;
    defaultProviderId?: null | string;
    defaultModelName?: null | string;
    extraConfig?: null | string;
};

export type UpdateProviderAccountInput = {
    name?: null | string;
    isEnabled?: null | boolean;
};

export type UpdateTaskInput = {
    title?: null | string;
    description?: null | string;
    status?: null | string;
    priority?: null | number | string;
    assignedProjectAgentRoleId?: null | string;
};

export type UpdateVendorProviderConfigurationInput = {
    configuration?: {
        [key: string]: unknown;
    };
};

export type VendorModelCatalogDto = {
    providerType?: string;
    status?: string;
    message?: null | string;
    missingConfigurationFields?: Array<string>;
    models?: Array<VendorModelDto>;
};

export type VendorModelDto = {
    id: string;
    name: string;
    family: null | string;
};

export type VendorProviderConfigurationDto = {
    providerType?: string;
    displayName?: string;
    avatarDataUri?: null | string;
    properties?: Array<VendorProviderConfigurationPropertyDto>;
    configuration?: {
        [key: string]: unknown;
    };
};

export type VendorProviderConfigurationPropertyDto = {
    name?: string;
    fieldType?: string;
    defaultValue?: unknown;
    required?: boolean;
};

export type GetApiAgentRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agent-roles';
};

export type GetApiAgentRolesResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<AgentRoleDto>;
        message?: string;
    };
};

export type GetApiAgentRolesResponse = GetApiAgentRolesResponses[keyof GetApiAgentRolesResponses];

export type PostApiAgentRolesData = {
    body: CreateAgentRoleInput;
    path?: never;
    query?: never;
    url: '/api/agent-roles';
};

export type PostApiAgentRolesResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: AgentRoleDto;
        message?: string;
    };
};

export type PostApiAgentRolesResponse = PostApiAgentRolesResponses[keyof PostApiAgentRolesResponses];

export type DeleteApiAgentRolesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agent-roles/{id}';
};

export type DeleteApiAgentRolesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiAgentRolesByIdResponse = DeleteApiAgentRolesByIdResponses[keyof DeleteApiAgentRolesByIdResponses];

export type GetApiAgentRolesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agent-roles/{id}';
};

export type GetApiAgentRolesByIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: AgentRoleDto;
        message?: string;
    };
};

export type GetApiAgentRolesByIdResponse = GetApiAgentRolesByIdResponses[keyof GetApiAgentRolesByIdResponses];

export type PutApiAgentRolesByIdData = {
    body: UpdateAgentRoleInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agent-roles/{id}';
};

export type PutApiAgentRolesByIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: AgentRoleDto;
        message?: string;
    };
};

export type PutApiAgentRolesByIdResponse = PutApiAgentRolesByIdResponses[keyof PutApiAgentRolesByIdResponses];

export type PostApiAgentRolesPreviewImportData = {
    body: PreviewAgentRoleTemplateImportInput;
    path?: never;
    query?: never;
    url: '/api/agent-roles/preview-import';
};

export type PostApiAgentRolesPreviewImportResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: PreviewAgentRoleTemplateImportResultDto;
        message?: string;
    };
};

export type PostApiAgentRolesPreviewImportResponse = PostApiAgentRolesPreviewImportResponses[keyof PostApiAgentRolesPreviewImportResponses];

export type PostApiAgentRolesImportData = {
    body: ImportAgentRoleTemplateInput;
    path?: never;
    query?: never;
    url: '/api/agent-roles/import';
};

export type PostApiAgentRolesImportResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ImportAgentRoleTemplateResultDto;
        message?: string;
    };
};

export type PostApiAgentRolesImportResponse = PostApiAgentRolesImportResponses[keyof PostApiAgentRolesImportResponses];

export type PostApiAgentRolesVendorByProviderTypeResetData = {
    body?: never;
    path: {
        providerType: string;
    };
    query?: never;
    url: '/api/agent-roles/vendor/{providerType}/reset';
};

export type PostApiAgentRolesVendorByProviderTypeResetResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiAgentRolesVendorByProviderTypeResetResponse = PostApiAgentRolesVendorByProviderTypeResetResponses[keyof PostApiAgentRolesVendorByProviderTypeResetResponses];

export type GetApiAgentRolesVendorByProviderTypeModelsData = {
    body?: never;
    path: {
        providerType: string;
    };
    query?: never;
    url: '/api/agent-roles/vendor/{providerType}/models';
};

export type GetApiAgentRolesVendorByProviderTypeModelsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<VendorModelDto>;
        message?: string;
    };
};

export type GetApiAgentRolesVendorByProviderTypeModelsResponse = GetApiAgentRolesVendorByProviderTypeModelsResponses[keyof GetApiAgentRolesVendorByProviderTypeModelsResponses];

export type GetApiAgentRolesVendorByProviderTypeModelCatalogData = {
    body?: never;
    path: {
        providerType: string;
    };
    query?: never;
    url: '/api/agent-roles/vendor/{providerType}/model-catalog';
};

export type GetApiAgentRolesVendorByProviderTypeModelCatalogResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: VendorModelCatalogDto;
        message?: string;
    };
};

export type GetApiAgentRolesVendorByProviderTypeModelCatalogResponse = GetApiAgentRolesVendorByProviderTypeModelCatalogResponses[keyof GetApiAgentRolesVendorByProviderTypeModelCatalogResponses];

export type GetApiAgentRolesVendorByProviderTypeConfigurationData = {
    body?: never;
    path: {
        providerType: string;
    };
    query?: never;
    url: '/api/agent-roles/vendor/{providerType}/configuration';
};

export type GetApiAgentRolesVendorByProviderTypeConfigurationResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: VendorProviderConfigurationDto;
        message?: string;
    };
};

export type GetApiAgentRolesVendorByProviderTypeConfigurationResponse = GetApiAgentRolesVendorByProviderTypeConfigurationResponses[keyof GetApiAgentRolesVendorByProviderTypeConfigurationResponses];

export type PutApiAgentRolesVendorByProviderTypeConfigurationData = {
    body: UpdateVendorProviderConfigurationInput;
    path: {
        providerType: string;
    };
    query?: never;
    url: '/api/agent-roles/vendor/{providerType}/configuration';
};

export type PutApiAgentRolesVendorByProviderTypeConfigurationResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: VendorProviderConfigurationDto;
        message?: string;
    };
};

export type PutApiAgentRolesVendorByProviderTypeConfigurationResponse = PutApiAgentRolesVendorByProviderTypeConfigurationResponses[keyof PutApiAgentRolesVendorByProviderTypeConfigurationResponses];

export type PostApiAgentRolesByIdTestChatData = {
    body: TestChatBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agent-roles/{id}/test-chat';
};

export type PostApiAgentRolesByIdTestChatResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ConversationTaskOutput;
        message?: string;
    };
};

export type PostApiAgentRolesByIdTestChatResponse = PostApiAgentRolesByIdTestChatResponses[keyof PostApiAgentRolesByIdTestChatResponses];

export type GetApiProjectsByProjectIdAgentsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/agents';
};

export type GetApiProjectsByProjectIdAgentsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<AgentDto>;
        message?: string;
    };
};

export type GetApiProjectsByProjectIdAgentsResponse = GetApiProjectsByProjectIdAgentsResponses[keyof GetApiProjectsByProjectIdAgentsResponses];

export type PutApiProjectsByProjectIdAgentsData = {
    body: SetAgentsBody;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/agents';
};

export type PutApiProjectsByProjectIdAgentsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ApiMessageDto;
        message?: string;
    };
};

export type PutApiProjectsByProjectIdAgentsResponse = PutApiProjectsByProjectIdAgentsResponses[keyof PutApiProjectsByProjectIdAgentsResponses];

export type GetApiProjectsByProjectIdAgentsByAgentIdEventsData = {
    body?: never;
    path: {
        projectId: string;
        agentId: string;
    };
    query?: {
        page?: number | string;
        pageSize?: number | string;
    };
    url: '/api/projects/{projectId}/agents/{agentId}/events';
};

export type GetApiProjectsByProjectIdAgentsByAgentIdEventsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: PagedAgentEventsDto;
        message?: string;
    };
};

export type GetApiProjectsByProjectIdAgentsByAgentIdEventsResponse = GetApiProjectsByProjectIdAgentsByAgentIdEventsResponses[keyof GetApiProjectsByProjectIdAgentsByAgentIdEventsResponses];

export type PostApiProjectsByProjectIdAgentsByAgentIdMessageData = {
    body: SendMessageBody;
    path: {
        projectId: string;
        agentId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/agents/{agentId}/message';
};

export type PostApiProjectsByProjectIdAgentsByAgentIdMessageResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ConversationTaskOutput;
        message?: string;
    };
};

export type PostApiProjectsByProjectIdAgentsByAgentIdMessageResponse = PostApiProjectsByProjectIdAgentsByAgentIdMessageResponses[keyof PostApiProjectsByProjectIdAgentsByAgentIdMessageResponses];

export type GetApiProjectsByProjectIdAgentsByAgentIdRuntimePreviewData = {
    body?: never;
    path: {
        projectId: string;
        agentId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/agents/{agentId}/runtime-preview';
};

export type GetApiProjectsByProjectIdAgentsByAgentIdRuntimePreviewResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: AgentRuntimePreviewDto;
        message?: string;
    };
};

export type GetApiProjectsByProjectIdAgentsByAgentIdRuntimePreviewResponse = GetApiProjectsByProjectIdAgentsByAgentIdRuntimePreviewResponses[keyof GetApiProjectsByProjectIdAgentsByAgentIdRuntimePreviewResponses];

export type GetApiAgentSoulsOptionsData = {
    body?: never;
    path?: never;
    query?: {
        locale?: string;
    };
    url: '/api/agent-souls/options';
};

export type GetApiAgentSoulsOptionsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: AgentSoulCatalogDto;
        message?: string;
    };
};

export type GetApiAgentSoulsOptionsResponse = GetApiAgentSoulsOptionsResponses[keyof GetApiAgentSoulsOptionsResponses];

export type GetApiProjectsByProjectIdFilesData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/files';
};

export type GetApiProjectsByProjectIdFilesResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<FileNodeDto>;
        message?: string;
    };
};

export type GetApiProjectsByProjectIdFilesResponse = GetApiProjectsByProjectIdFilesResponses[keyof GetApiProjectsByProjectIdFilesResponses];

export type GetApiProjectsByProjectIdFilesContentData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        path?: string;
    };
    url: '/api/projects/{projectId}/files/content';
};

export type GetApiProjectsByProjectIdFilesContentResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ContentDto;
        message?: string;
    };
};

export type GetApiProjectsByProjectIdFilesContentResponse = GetApiProjectsByProjectIdFilesContentResponses[keyof GetApiProjectsByProjectIdFilesContentResponses];

export type GetApiProjectsByProjectIdFilesDiffData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        commitSha?: string;
    };
    url: '/api/projects/{projectId}/files/diff';
};

export type GetApiProjectsByProjectIdFilesDiffResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: DiffDto;
        message?: string;
    };
};

export type GetApiProjectsByProjectIdFilesDiffResponse = GetApiProjectsByProjectIdFilesDiffResponses[keyof GetApiProjectsByProjectIdFilesDiffResponses];

export type GetApiProjectsByProjectIdCheckpointsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/checkpoints';
};

export type GetApiProjectsByProjectIdCheckpointsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<CheckpointDto>;
        message?: string;
    };
};

export type GetApiProjectsByProjectIdCheckpointsResponse = GetApiProjectsByProjectIdCheckpointsResponses[keyof GetApiProjectsByProjectIdCheckpointsResponses];

export type GetApiMcpMarketplaceSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mcp/marketplace/sources';
};

export type GetApiMcpMarketplaceSourcesResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<MarketplaceSourceDto>;
        message?: string;
    };
};

export type GetApiMcpMarketplaceSourcesResponse = GetApiMcpMarketplaceSourcesResponses[keyof GetApiMcpMarketplaceSourcesResponses];

export type GetApiMcpMarketplaceSearchData = {
    body?: never;
    path?: never;
    query?: {
        SourceKey?: string;
        Keyword?: string;
        Category?: string;
        Cursor?: string;
        Page?: number | string;
        PageSize?: number | string;
    };
    url: '/api/mcp/marketplace/search';
};

export type GetApiMcpMarketplaceSearchResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: MarketplaceSearchResultDto;
        message?: string;
    };
};

export type GetApiMcpMarketplaceSearchResponse = GetApiMcpMarketplaceSearchResponses[keyof GetApiMcpMarketplaceSearchResponses];

export type PostApiMcpMarketplaceInstallData = {
    body: InstallFromMarketplaceInput;
    path?: never;
    query?: never;
    url: '/api/mcp/marketplace/install';
};

export type PostApiMcpMarketplaceInstallResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: MarketplaceServerDto;
        message?: string;
    };
};

export type PostApiMcpMarketplaceInstallResponse = PostApiMcpMarketplaceInstallResponses[keyof PostApiMcpMarketplaceInstallResponses];

export type GetApiMcpSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mcp/sources';
};

export type GetApiMcpSourcesResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<McpSourceDto>;
        message?: string;
    };
};

export type GetApiMcpSourcesResponse = GetApiMcpSourcesResponses[keyof GetApiMcpSourcesResponses];

export type GetApiMcpCatalogSearchData = {
    body?: never;
    path?: never;
    query?: {
        SourceKey?: string;
        Keyword?: string;
        Category?: string;
        TransportType?: string;
        Cursor?: string;
        Page?: number | string;
        PageSize?: number | string;
    };
    url: '/api/mcp/catalog/search';
};

export type GetApiMcpCatalogSearchResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpCatalogSearchResultDto;
        message?: string;
    };
};

export type GetApiMcpCatalogSearchResponse = GetApiMcpCatalogSearchResponses[keyof GetApiMcpCatalogSearchResponses];

export type GetApiMcpCatalogEntryData = {
    body?: never;
    path?: never;
    query?: {
        sourceKey?: string;
        entryId?: string;
    };
    url: '/api/mcp/catalog/entry';
};

export type GetApiMcpCatalogEntryResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpCatalogEntryDto;
        message?: string;
    };
};

export type GetApiMcpCatalogEntryResponse = GetApiMcpCatalogEntryResponses[keyof GetApiMcpCatalogEntryResponses];

export type PostApiMcpInstallData = {
    body: InstallMcpServerInput;
    path?: never;
    query?: never;
    url: '/api/mcp/install';
};

export type PostApiMcpInstallResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpServerDto;
        message?: string;
    };
};

export type PostApiMcpInstallResponse = PostApiMcpInstallResponses[keyof PostApiMcpInstallResponses];

export type GetApiMcpServersData = {
    body?: never;
    path?: never;
    query?: {
        source?: string;
        category?: string;
        search?: string;
        enabledState?: boolean;
        installedState?: string;
    };
    url: '/api/mcp/servers';
};

export type GetApiMcpServersResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<McpServerDto>;
        message?: string;
    };
};

export type GetApiMcpServersResponse = GetApiMcpServersResponses[keyof GetApiMcpServersResponses];

export type PostApiMcpServersData = {
    body: CreateMcpServerInput;
    path?: never;
    query?: never;
    url: '/api/mcp/servers';
};

export type PostApiMcpServersResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpServerDto;
        message?: string;
    };
};

export type PostApiMcpServersResponse = PostApiMcpServersResponses[keyof PostApiMcpServersResponses];

export type DeleteApiMcpServersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/mcp/servers/{id}';
};

export type DeleteApiMcpServersByIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: DeleteMcpServerResultDto;
        message?: string;
    };
};

export type DeleteApiMcpServersByIdResponse = DeleteApiMcpServersByIdResponses[keyof DeleteApiMcpServersByIdResponses];

export type GetApiMcpServersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/mcp/servers/{id}';
};

export type GetApiMcpServersByIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpServerDto;
        message?: string;
    };
};

export type GetApiMcpServersByIdResponse = GetApiMcpServersByIdResponses[keyof GetApiMcpServersByIdResponses];

export type PutApiMcpServersByIdData = {
    body: UpdateMcpServerInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/mcp/servers/{id}';
};

export type PutApiMcpServersByIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpServerDto;
        message?: string;
    };
};

export type PutApiMcpServersByIdResponse = PutApiMcpServersByIdResponses[keyof PutApiMcpServersByIdResponses];

export type GetApiMcpServersByIdUninstallCheckData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/mcp/servers/{id}/uninstall-check';
};

export type GetApiMcpServersByIdUninstallCheckResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpUninstallCheckResultDto;
        message?: string;
    };
};

export type GetApiMcpServersByIdUninstallCheckResponse = GetApiMcpServersByIdUninstallCheckResponses[keyof GetApiMcpServersByIdUninstallCheckResponses];

export type PostApiMcpServersByIdRepairData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/mcp/servers/{id}/repair';
};

export type PostApiMcpServersByIdRepairResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpRepairResultDto;
        message?: string;
    };
};

export type PostApiMcpServersByIdRepairResponse = PostApiMcpServersByIdRepairResponses[keyof PostApiMcpServersByIdRepairResponses];

export type GetApiMcpServersByMcpServerIdConfigsData = {
    body?: never;
    path: {
        mcpServerId: string;
    };
    query?: never;
    url: '/api/mcp/servers/{mcpServerId}/configs';
};

export type GetApiMcpServersByMcpServerIdConfigsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<McpServerConfigDto>;
        message?: string;
    };
};

export type GetApiMcpServersByMcpServerIdConfigsResponse = GetApiMcpServersByMcpServerIdConfigsResponses[keyof GetApiMcpServersByMcpServerIdConfigsResponses];

export type GetApiMcpConfigsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mcp/configs';
};

export type GetApiMcpConfigsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<McpServerConfigDto>;
        message?: string;
    };
};

export type GetApiMcpConfigsResponse = GetApiMcpConfigsResponses[keyof GetApiMcpConfigsResponses];

export type PostApiMcpConfigsData = {
    body: CreateMcpServerConfigInput;
    path?: never;
    query?: never;
    url: '/api/mcp/configs';
};

export type PostApiMcpConfigsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpServerConfigDto;
        message?: string;
    };
};

export type PostApiMcpConfigsResponse = PostApiMcpConfigsResponses[keyof PostApiMcpConfigsResponses];

export type DeleteApiMcpConfigsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/mcp/configs/{id}';
};

export type DeleteApiMcpConfigsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiMcpConfigsByIdResponse = DeleteApiMcpConfigsByIdResponses[keyof DeleteApiMcpConfigsByIdResponses];

export type GetApiMcpConfigsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/mcp/configs/{id}';
};

export type GetApiMcpConfigsByIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpServerConfigDto;
        message?: string;
    };
};

export type GetApiMcpConfigsByIdResponse = GetApiMcpConfigsByIdResponses[keyof GetApiMcpConfigsByIdResponses];

export type PutApiMcpConfigsByIdData = {
    body: UpdateMcpServerConfigInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/mcp/configs/{id}';
};

export type PutApiMcpConfigsByIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpServerConfigDto;
        message?: string;
    };
};

export type PutApiMcpConfigsByIdResponse = PutApiMcpConfigsByIdResponses[keyof PutApiMcpConfigsByIdResponses];

export type PostApiMcpConfigsByIdTestData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/mcp/configs/{id}/test';
};

export type PostApiMcpConfigsByIdTestResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: TestMcpConnectionResult;
        message?: string;
    };
};

export type PostApiMcpConfigsByIdTestResponse = PostApiMcpConfigsByIdTestResponses[keyof PostApiMcpConfigsByIdTestResponses];

export type PostApiMcpConfigsTestDraftData = {
    body: TestMcpConnectionDraftInput;
    path?: never;
    query?: never;
    url: '/api/mcp/configs/test-draft';
};

export type PostApiMcpConfigsTestDraftResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: TestMcpConnectionResult;
        message?: string;
    };
};

export type PostApiMcpConfigsTestDraftResponse = PostApiMcpConfigsTestDraftResponses[keyof PostApiMcpConfigsTestDraftResponses];

export type GetApiMcpAgentBindingsByAgentRoleIdData = {
    body?: never;
    path: {
        agentRoleId: string;
    };
    query?: never;
    url: '/api/mcp/agent-bindings/{agentRoleId}';
};

export type GetApiMcpAgentBindingsByAgentRoleIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<AgentRoleMcpBindingDto>;
        message?: string;
    };
};

export type GetApiMcpAgentBindingsByAgentRoleIdResponse = GetApiMcpAgentBindingsByAgentRoleIdResponses[keyof GetApiMcpAgentBindingsByAgentRoleIdResponses];

export type PutApiMcpAgentBindingsByAgentRoleIdData = {
    body: Array<AgentRoleMcpBindingInput>;
    path: {
        agentRoleId: string;
    };
    query?: never;
    url: '/api/mcp/agent-bindings/{agentRoleId}';
};

export type PutApiMcpAgentBindingsByAgentRoleIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiMcpAgentBindingsByAgentRoleIdResponse = PutApiMcpAgentBindingsByAgentRoleIdResponses[keyof PutApiMcpAgentBindingsByAgentRoleIdResponses];

export type PostApiMcpBindingDraftData = {
    body: CreateMcpBindingDraftInput;
    path?: never;
    query?: never;
    url: '/api/mcp/binding-draft';
};

export type PostApiMcpBindingDraftResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: McpBindingDraftDto;
        message?: string;
    };
};

export type PostApiMcpBindingDraftResponse = PostApiMcpBindingDraftResponses[keyof PostApiMcpBindingDraftResponses];

export type GetApiMcpProjectAgentBindingsByProjectAgentIdData = {
    body?: never;
    path: {
        projectAgentId: string;
    };
    query?: never;
    url: '/api/mcp/project-agent-bindings/{projectAgentId}';
};

export type GetApiMcpProjectAgentBindingsByProjectAgentIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<ProjectAgentMcpBindingDto>;
        message?: string;
    };
};

export type GetApiMcpProjectAgentBindingsByProjectAgentIdResponse = GetApiMcpProjectAgentBindingsByProjectAgentIdResponses[keyof GetApiMcpProjectAgentBindingsByProjectAgentIdResponses];

export type PutApiMcpProjectAgentBindingsByProjectAgentIdData = {
    body: Array<ProjectAgentMcpBindingInput>;
    path: {
        projectAgentId: string;
    };
    query?: never;
    url: '/api/mcp/project-agent-bindings/{projectAgentId}';
};

export type PutApiMcpProjectAgentBindingsByProjectAgentIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiMcpProjectAgentBindingsByProjectAgentIdResponse = PutApiMcpProjectAgentBindingsByProjectAgentIdResponses[keyof PutApiMcpProjectAgentBindingsByProjectAgentIdResponses];

export type GetApiModelsDevStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/models-dev/status';
};

export type GetApiModelsDevStatusResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ModelDataStatusDto;
        message?: string;
    };
};

export type GetApiModelsDevStatusResponse = GetApiModelsDevStatusResponses[keyof GetApiModelsDevStatusResponses];

export type PostApiModelsDevRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/models-dev/refresh';
};

export type PostApiModelsDevRefreshResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ModelDataStatusDto;
        message?: string;
    };
};

export type PostApiModelsDevRefreshResponse = PostApiModelsDevRefreshResponses[keyof PostApiModelsDevRefreshResponses];

export type GetApiModelsDevProvidersByProviderKeyModelsData = {
    body?: never;
    path: {
        providerKey: string;
    };
    query?: never;
    url: '/api/models-dev/providers/{providerKey}/models';
};

export type GetApiModelsDevProvidersByProviderKeyModelsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<ModelDataDto>;
        message?: string;
    };
};

export type GetApiModelsDevProvidersByProviderKeyModelsResponse = GetApiModelsDevProvidersByProviderKeyModelsResponses[keyof GetApiModelsDevProvidersByProviderKeyModelsResponses];

export type GetApiModelsDevProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/models-dev/providers';
};

export type GetApiModelsDevProvidersResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<ModelDataProviderDto>;
        message?: string;
    };
};

export type GetApiModelsDevProvidersResponse = GetApiModelsDevProvidersResponses[keyof GetApiModelsDevProvidersResponses];

export type GetApiMonitorHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/monitor/health';
};

export type GetApiMonitorHealthResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: HealthStatusDto;
        message?: string;
    };
};

export type GetApiMonitorHealthResponse = GetApiMonitorHealthResponses[keyof GetApiMonitorHealthResponses];

export type GetApiMonitorStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/monitor/stats';
};

export type GetApiMonitorStatsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: SystemStatsDto;
        message?: string;
    };
};

export type GetApiMonitorStatsResponse = GetApiMonitorStatsResponses[keyof GetApiMonitorStatsResponses];

export type GetApiMonitorProjectsByProjectIdStatsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/monitor/projects/{projectId}/stats';
};

export type GetApiMonitorProjectsByProjectIdStatsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ProjectStatsDto;
        message?: string;
    };
};

export type GetApiMonitorProjectsByProjectIdStatsResponse = GetApiMonitorProjectsByProjectIdStatsResponses[keyof GetApiMonitorProjectsByProjectIdStatsResponses];

export type GetApiMonitorProjectsByProjectIdEventsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        page?: number | string;
        pageSize?: number | string;
        eventType?: string;
        scene?: string;
    };
    url: '/api/monitor/projects/{projectId}/events';
};

export type GetApiMonitorProjectsByProjectIdEventsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: PagedResultOfEventDto;
        message?: string;
    };
};

export type GetApiMonitorProjectsByProjectIdEventsResponse = GetApiMonitorProjectsByProjectIdEventsResponses[keyof GetApiMonitorProjectsByProjectIdEventsResponses];

export type PostApiPermissionRequestsListenersData = {
    body?: null | PermissionListenerRegistrationBody;
    path?: never;
    query?: never;
    url: '/api/permission-requests/listeners';
};

export type PostApiPermissionRequestsListenersResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: PermissionListenerLease;
        message?: string;
    };
};

export type PostApiPermissionRequestsListenersResponse = PostApiPermissionRequestsListenersResponses[keyof PostApiPermissionRequestsListenersResponses];

export type DeleteApiPermissionRequestsListenersByListenerIdData = {
    body?: never;
    path: {
        listenerId: string;
    };
    query?: never;
    url: '/api/permission-requests/listeners/{listenerId}';
};

export type DeleteApiPermissionRequestsListenersByListenerIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ApiStatusDto;
        message?: string;
    };
};

export type DeleteApiPermissionRequestsListenersByListenerIdResponse = DeleteApiPermissionRequestsListenersByListenerIdResponses[keyof DeleteApiPermissionRequestsListenersByListenerIdResponses];

export type PostApiPermissionRequestsByRequestIdResponsesData = {
    body: PermissionRequestResponseBody;
    path: {
        requestId: string;
    };
    query?: never;
    url: '/api/permission-requests/{requestId}/responses';
};

export type PostApiPermissionRequestsByRequestIdResponsesResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: PermissionAuthorizationSubmitResult;
        message?: string;
    };
};

export type PostApiPermissionRequestsByRequestIdResponsesResponse = PostApiPermissionRequestsByRequestIdResponsesResponses[keyof PostApiPermissionRequestsByRequestIdResponsesResponses];

export type GetApiProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type GetApiProjectsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<ProjectDto>;
        message?: string;
    };
};

export type GetApiProjectsResponse = GetApiProjectsResponses[keyof GetApiProjectsResponses];

export type PostApiProjectsData = {
    body: CreateProjectInput;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type PostApiProjectsResponses = {
    /**
     * Created
     */
    201: {
        success: boolean;
        data: ProjectDto;
        message?: string;
    };
};

export type PostApiProjectsResponse = PostApiProjectsResponses[keyof PostApiProjectsResponses];

export type DeleteApiProjectsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type DeleteApiProjectsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiProjectsByIdResponse = DeleteApiProjectsByIdResponses[keyof DeleteApiProjectsByIdResponses];

export type GetApiProjectsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type GetApiProjectsByIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ProjectDto;
        message?: string;
    };
};

export type GetApiProjectsByIdResponse = GetApiProjectsByIdResponses[keyof GetApiProjectsByIdResponses];

export type PutApiProjectsByIdData = {
    body: UpdateProjectInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type PutApiProjectsByIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ProjectDto;
        message?: string;
    };
};

export type PutApiProjectsByIdResponse = PutApiProjectsByIdResponses[keyof PutApiProjectsByIdResponses];

export type GetApiProjectsByIdReadmeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}/readme';
};

export type GetApiProjectsByIdReadmeResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ContentDto;
        message?: string;
    };
};

export type GetApiProjectsByIdReadmeResponse = GetApiProjectsByIdReadmeResponses[keyof GetApiProjectsByIdReadmeResponses];

export type PostApiProjectsByIdInitializeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}/initialize';
};

export type PostApiProjectsByIdInitializeResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ProjectDto;
        message?: string;
    };
};

export type PostApiProjectsByIdInitializeResponse = PostApiProjectsByIdInitializeResponses[keyof PostApiProjectsByIdInitializeResponses];

export type PostApiProjectsByIdStartData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}/start';
};

export type PostApiProjectsByIdStartResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ProjectDto;
        message?: string;
    };
};

export type PostApiProjectsByIdStartResponse = PostApiProjectsByIdStartResponses[keyof PostApiProjectsByIdStartResponses];

export type PostApiProjectsByIdExportData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}/export';
};

export type PostApiProjectsByIdExportResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type PostApiProjectsByIdExportResponse = PostApiProjectsByIdExportResponses[keyof PostApiProjectsByIdExportResponses];

export type PostApiProjectsImportData = {
    body: {
        file?: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/api/projects/import';
};

export type PostApiProjectsImportResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ProjectDto;
        message?: string;
    };
};

export type PostApiProjectsImportResponse = PostApiProjectsImportResponses[keyof PostApiProjectsImportResponses];

export type GetApiProtocolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/protocols';
};

export type GetApiProtocolsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<ProtocolMetadata>;
        message?: string;
    };
};

export type GetApiProtocolsResponse = GetApiProtocolsResponses[keyof GetApiProtocolsResponses];

export type GetApiProviderAccountsData = {
    body?: never;
    path?: never;
    query?: {
        ProtocolTypes?: Array<string>;
        IsEnabled?: boolean;
    };
    url: '/api/provider-accounts';
};

export type GetApiProviderAccountsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: PagedResultOfProviderAccountDto;
        message?: string;
    };
};

export type GetApiProviderAccountsResponse = GetApiProviderAccountsResponses[keyof GetApiProviderAccountsResponses];

export type PostApiProviderAccountsData = {
    body: CreateProviderAccountInput;
    path?: never;
    query?: never;
    url: '/api/provider-accounts';
};

export type PostApiProviderAccountsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ProviderAccountDto;
        message?: string;
    };
};

export type PostApiProviderAccountsResponse = PostApiProviderAccountsResponses[keyof PostApiProviderAccountsResponses];

export type GetApiProviderAccountsProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/provider-accounts/providers';
};

export type GetApiProviderAccountsProvidersResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<ProviderInfo>;
        message?: string;
    };
};

export type GetApiProviderAccountsProvidersResponse = GetApiProviderAccountsProvidersResponses[keyof GetApiProviderAccountsProvidersResponses];

export type DeleteApiProviderAccountsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/provider-accounts/{id}';
};

export type DeleteApiProviderAccountsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiProviderAccountsByIdResponse = DeleteApiProviderAccountsByIdResponses[keyof DeleteApiProviderAccountsByIdResponses];

export type GetApiProviderAccountsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/provider-accounts/{id}';
};

export type GetApiProviderAccountsByIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ProviderAccountDto;
        message?: string;
    };
};

export type GetApiProviderAccountsByIdResponse = GetApiProviderAccountsByIdResponses[keyof GetApiProviderAccountsByIdResponses];

export type PutApiProviderAccountsByIdData = {
    body: UpdateProviderAccountInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/provider-accounts/{id}';
};

export type PutApiProviderAccountsByIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ProviderAccountDto;
        message?: string;
    };
};

export type PutApiProviderAccountsByIdResponse = PutApiProviderAccountsByIdResponses[keyof PutApiProviderAccountsByIdResponses];

export type GetApiProviderAccountsByIdConfigurationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/provider-accounts/{id}/configuration';
};

export type GetApiProviderAccountsByIdConfigurationResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: GetConfigurationResultOfJsonElement;
        message?: string;
    };
};

export type GetApiProviderAccountsByIdConfigurationResponse = GetApiProviderAccountsByIdConfigurationResponses[keyof GetApiProviderAccountsByIdConfigurationResponses];

export type PutApiProviderAccountsByIdConfigurationData = {
    body: JsonElement;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/provider-accounts/{id}/configuration';
};

export type PutApiProviderAccountsByIdConfigurationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiProviderAccountsByIdConfigurationResponse = PutApiProviderAccountsByIdConfigurationResponses[keyof PutApiProviderAccountsByIdConfigurationResponses];

export type GetApiProviderAccountsByIdModelsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/provider-accounts/{id}/models';
};

export type GetApiProviderAccountsByIdModelsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<ProviderModelDto>;
        message?: string;
    };
};

export type GetApiProviderAccountsByIdModelsResponse = GetApiProviderAccountsByIdModelsResponses[keyof GetApiProviderAccountsByIdModelsResponses];

export type DeleteApiProviderAccountsByIdDeviceAuthData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/provider-accounts/{id}/device-auth';
};

export type DeleteApiProviderAccountsByIdDeviceAuthResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiProviderAccountsByIdDeviceAuthResponse = DeleteApiProviderAccountsByIdDeviceAuthResponses[keyof DeleteApiProviderAccountsByIdDeviceAuthResponses];

export type PostApiProviderAccountsByIdDeviceAuthData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/provider-accounts/{id}/device-auth';
};

export type PostApiProviderAccountsByIdDeviceAuthResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: DeviceCodeDto;
        message?: string;
    };
};

export type PostApiProviderAccountsByIdDeviceAuthResponse = PostApiProviderAccountsByIdDeviceAuthResponses[keyof PostApiProviderAccountsByIdDeviceAuthResponses];

export type PostApiProviderAccountsByIdDeviceAuthPollData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/provider-accounts/{id}/device-auth/poll';
};

export type PostApiProviderAccountsByIdDeviceAuthPollResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: DeviceAuthPollDto;
        message?: string;
    };
};

export type PostApiProviderAccountsByIdDeviceAuthPollResponse = PostApiProviderAccountsByIdDeviceAuthPollResponses[keyof PostApiProviderAccountsByIdDeviceAuthPollResponses];

export type PostApiSessionsData = {
    body: CreateSessionInput;
    path?: never;
    query?: never;
    url: '/api/sessions';
};

export type PostApiSessionsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ConversationTaskOutput;
        message?: string;
    };
};

export type PostApiSessionsResponse = PostApiSessionsResponses[keyof PostApiSessionsResponses];

export type PostApiSessionsBySessionIdMessagesData = {
    body: ChatMessageRequest;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/sessions/{sessionId}/messages';
};

export type PostApiSessionsBySessionIdMessagesResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ConversationTaskOutput;
        message?: string;
    };
};

export type PostApiSessionsBySessionIdMessagesResponse = PostApiSessionsBySessionIdMessagesResponses[keyof PostApiSessionsBySessionIdMessagesResponses];

export type GetApiSessionsBySessionIdData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/sessions/{sessionId}';
};

export type GetApiSessionsBySessionIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: SessionDto;
        message?: string;
    };
};

export type GetApiSessionsBySessionIdResponse = GetApiSessionsBySessionIdResponses[keyof GetApiSessionsBySessionIdResponses];

export type GetApiSessionsBySessionIdEventsData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/sessions/{sessionId}/events';
};

export type GetApiSessionsBySessionIdEventsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<SessionEventDto>;
        message?: string;
    };
};

export type GetApiSessionsBySessionIdEventsResponse = GetApiSessionsBySessionIdEventsResponses[keyof GetApiSessionsBySessionIdEventsResponses];

export type GetApiSessionsBySessionIdFramesByFrameIdMessagesData = {
    body?: never;
    path: {
        sessionId: string;
        frameId: string;
    };
    query?: never;
    url: '/api/sessions/{sessionId}/frames/{frameId}/messages';
};

export type GetApiSessionsBySessionIdFramesByFrameIdMessagesResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<ChatMessageDto>;
        message?: string;
    };
};

export type GetApiSessionsBySessionIdFramesByFrameIdMessagesResponse = GetApiSessionsBySessionIdFramesByFrameIdMessagesResponses[keyof GetApiSessionsBySessionIdFramesByFrameIdMessagesResponses];

export type PostApiSessionsBySessionIdCancelData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/sessions/{sessionId}/cancel';
};

export type PostApiSessionsBySessionIdCancelResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ApiStatusDto;
        message?: string;
    };
};

export type PostApiSessionsBySessionIdCancelResponse = PostApiSessionsBySessionIdCancelResponses[keyof PostApiSessionsBySessionIdCancelResponses];

export type PostApiSessionsBySessionIdPopData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/sessions/{sessionId}/pop';
};

export type PostApiSessionsBySessionIdPopResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ApiStatusDto;
        message?: string;
    };
};

export type PostApiSessionsBySessionIdPopResponse = PostApiSessionsBySessionIdPopResponses[keyof PostApiSessionsBySessionIdPopResponses];

export type GetApiSessionsByProjectByProjectIdData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        limit?: number | string;
        scene?: string;
    };
    url: '/api/sessions/by-project/{projectId}';
};

export type GetApiSessionsByProjectByProjectIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<SessionDto>;
        message?: string;
    };
};

export type GetApiSessionsByProjectByProjectIdResponse = GetApiSessionsByProjectByProjectIdResponses[keyof GetApiSessionsByProjectByProjectIdResponses];

export type GetApiSessionsByProjectByProjectIdActiveData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        scene?: string;
    };
    url: '/api/sessions/by-project/{projectId}/active';
};

export type GetApiSessionsByProjectByProjectIdActiveResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: SessionDto;
        message?: string;
    };
};

export type GetApiSessionsByProjectByProjectIdActiveResponse = GetApiSessionsByProjectByProjectIdActiveResponses[keyof GetApiSessionsByProjectByProjectIdActiveResponses];

export type GetApiSessionsBySessionIdChatMessagesData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: {
        skip?: number | string;
        take?: number | string;
    };
    url: '/api/sessions/{sessionId}/chat-messages';
};

export type GetApiSessionsBySessionIdChatMessagesResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ChatMessageListOutput;
        message?: string;
    };
};

export type GetApiSessionsBySessionIdChatMessagesResponse = GetApiSessionsBySessionIdChatMessagesResponses[keyof GetApiSessionsBySessionIdChatMessagesResponses];

export type GetApiSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type GetApiSettingsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: {
            [key: string]: string;
        };
        message?: string;
    };
};

export type GetApiSettingsResponse = GetApiSettingsResponses[keyof GetApiSettingsResponses];

export type PutApiSettingsData = {
    body: {
        [key: string]: string;
    };
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type PutApiSettingsResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ApiMessageDto;
        message?: string;
    };
};

export type PutApiSettingsResponse = PutApiSettingsResponses[keyof PutApiSettingsResponses];

export type GetApiSettingsSystemData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/system';
};

export type GetApiSettingsSystemResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: SystemSettingsDto;
        message?: string;
    };
};

export type GetApiSettingsSystemResponse = GetApiSettingsSystemResponses[keyof GetApiSettingsSystemResponses];

export type PutApiSettingsSystemData = {
    body: SystemSettingsDto;
    path?: never;
    query?: never;
    url: '/api/settings/system';
};

export type PutApiSettingsSystemResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ApiMessageDto;
        message?: string;
    };
};

export type PutApiSettingsSystemResponse = PutApiSettingsSystemResponses[keyof PutApiSettingsSystemResponses];

export type GetApiSkillsCatalogData = {
    body?: never;
    path?: never;
    query?: {
        Query?: string;
        Owner?: string;
        Repo?: string;
        SortBy?: string;
        SortOrder?: string;
        Page?: number | string;
        PageSize?: number | string;
    };
    url: '/api/skills/catalog';
};

export type GetApiSkillsCatalogResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: SkillCatalogPageDto;
        message?: string;
    };
};

export type GetApiSkillsCatalogResponse = GetApiSkillsCatalogResponses[keyof GetApiSkillsCatalogResponses];

export type GetApiSkillsSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/skills/sources';
};

export type GetApiSkillsSourcesResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<SkillCatalogSourceDto>;
        message?: string;
    };
};

export type GetApiSkillsSourcesResponse = GetApiSkillsSourcesResponses[keyof GetApiSkillsSourcesResponses];

export type GetApiSkillsCatalogByOwnerByRepoBySkillIdData = {
    body?: never;
    path: {
        owner: string;
        repo: string;
        skillId: string;
    };
    query?: never;
    url: '/api/skills/catalog/{owner}/{repo}/{skillId}';
};

export type GetApiSkillsCatalogByOwnerByRepoBySkillIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: SkillCatalogItemDto;
        message?: string;
    };
};

export type GetApiSkillsCatalogByOwnerByRepoBySkillIdResponse = GetApiSkillsCatalogByOwnerByRepoBySkillIdResponses[keyof GetApiSkillsCatalogByOwnerByRepoBySkillIdResponses];

export type GetApiSkillsInstalledData = {
    body?: never;
    path?: never;
    query?: {
        Query?: string;
    };
    url: '/api/skills/installed';
};

export type GetApiSkillsInstalledResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<InstalledSkillDto>;
        message?: string;
    };
};

export type GetApiSkillsInstalledResponse = GetApiSkillsInstalledResponses[keyof GetApiSkillsInstalledResponses];

export type PostApiSkillsInstallData = {
    body: InstallSkillInput;
    path?: never;
    query?: never;
    url: '/api/skills/install';
};

export type PostApiSkillsInstallResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: InstalledSkillDto;
        message?: string;
    };
};

export type PostApiSkillsInstallResponse = PostApiSkillsInstallResponses[keyof PostApiSkillsInstallResponses];

export type PostApiSkillsUninstallData = {
    body: UninstallSkillInput;
    path?: never;
    query?: never;
    url: '/api/skills/uninstall';
};

export type PostApiSkillsUninstallResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: boolean;
        message?: string;
    };
};

export type PostApiSkillsUninstallResponse = PostApiSkillsUninstallResponses[keyof PostApiSkillsUninstallResponses];

export type GetApiSkillsAgentBindingsByAgentRoleIdData = {
    body?: never;
    path: {
        agentRoleId: string;
    };
    query?: never;
    url: '/api/skills/agent-bindings/{agentRoleId}';
};

export type GetApiSkillsAgentBindingsByAgentRoleIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<AgentRoleSkillBindingDto>;
        message?: string;
    };
};

export type GetApiSkillsAgentBindingsByAgentRoleIdResponse = GetApiSkillsAgentBindingsByAgentRoleIdResponses[keyof GetApiSkillsAgentBindingsByAgentRoleIdResponses];

export type PutApiSkillsAgentBindingsByAgentRoleIdData = {
    body?: null | Array<AgentRoleSkillBindingInput>;
    path: {
        agentRoleId: string;
    };
    query?: never;
    url: '/api/skills/agent-bindings/{agentRoleId}';
};

export type PutApiSkillsAgentBindingsByAgentRoleIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTalentMarketSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/talent-market/sources';
};

export type GetApiTalentMarketSourcesResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<TalentMarketSourceDto>;
        message?: string;
    };
};

export type GetApiTalentMarketSourcesResponse = GetApiTalentMarketSourcesResponses[keyof GetApiTalentMarketSourcesResponses];

export type GetApiTalentMarketSearchData = {
    body?: never;
    path?: never;
    query?: {
        SourceKey?: string;
        Keyword?: string;
        Page?: number | string;
        PageSize?: number | string;
    };
    url: '/api/talent-market/search';
};

export type GetApiTalentMarketSearchResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: TalentMarketSearchResultDto;
        message?: string;
    };
};

export type GetApiTalentMarketSearchResponse = GetApiTalentMarketSearchResponses[keyof GetApiTalentMarketSearchResponses];

export type PostApiTalentMarketPreviewHireData = {
    body: PreviewTalentMarketHireInput;
    path?: never;
    query?: never;
    url: '/api/talent-market/preview-hire';
};

export type PostApiTalentMarketPreviewHireResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: TalentMarketHirePreviewDto;
        message?: string;
    };
};

export type PostApiTalentMarketPreviewHireResponse = PostApiTalentMarketPreviewHireResponses[keyof PostApiTalentMarketPreviewHireResponses];

export type PostApiTalentMarketHireData = {
    body: HireTalentMarketRoleInput;
    path?: never;
    query?: never;
    url: '/api/talent-market/hire';
};

export type PostApiTalentMarketHireResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: ImportAgentRoleTemplateResultDto;
        message?: string;
    };
};

export type PostApiTalentMarketHireResponse = PostApiTalentMarketHireResponses[keyof PostApiTalentMarketHireResponses];

export type GetApiProjectsByProjectIdTasksData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        status?: string;
    };
    url: '/api/projects/{projectId}/tasks';
};

export type GetApiProjectsByProjectIdTasksResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<TaskDto>;
        message?: string;
    };
};

export type GetApiProjectsByProjectIdTasksResponse = GetApiProjectsByProjectIdTasksResponses[keyof GetApiProjectsByProjectIdTasksResponses];

export type PostApiProjectsByProjectIdTasksData = {
    body: CreateTaskInput;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/tasks';
};

export type PostApiProjectsByProjectIdTasksResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: TaskDto;
        message?: string;
    };
};

export type PostApiProjectsByProjectIdTasksResponse = PostApiProjectsByProjectIdTasksResponses[keyof PostApiProjectsByProjectIdTasksResponses];

export type DeleteApiProjectsByProjectIdTasksByTaskIdData = {
    body?: never;
    path: {
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/tasks/{taskId}';
};

export type DeleteApiProjectsByProjectIdTasksByTaskIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiProjectsByProjectIdTasksByTaskIdResponse = DeleteApiProjectsByProjectIdTasksByTaskIdResponses[keyof DeleteApiProjectsByProjectIdTasksByTaskIdResponses];

export type GetApiProjectsByProjectIdTasksByTaskIdData = {
    body?: never;
    path: {
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/tasks/{taskId}';
};

export type GetApiProjectsByProjectIdTasksByTaskIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: TaskDto;
        message?: string;
    };
};

export type GetApiProjectsByProjectIdTasksByTaskIdResponse = GetApiProjectsByProjectIdTasksByTaskIdResponses[keyof GetApiProjectsByProjectIdTasksByTaskIdResponses];

export type PutApiProjectsByProjectIdTasksByTaskIdData = {
    body: UpdateTaskInput;
    path: {
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/tasks/{taskId}';
};

export type PutApiProjectsByProjectIdTasksByTaskIdResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: TaskDto;
        message?: string;
    };
};

export type PutApiProjectsByProjectIdTasksByTaskIdResponse = PutApiProjectsByProjectIdTasksByTaskIdResponses[keyof PutApiProjectsByProjectIdTasksByTaskIdResponses];

export type PostApiProjectsByProjectIdTasksByTaskIdResumeData = {
    body?: never;
    path: {
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/tasks/{taskId}/resume';
};

export type PostApiProjectsByProjectIdTasksByTaskIdResumeResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetApiProjectsByProjectIdTasksByTaskIdTimelineData = {
    body?: never;
    path: {
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/tasks/{taskId}/timeline';
};

export type GetApiProjectsByProjectIdTasksByTaskIdTimelineResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: Array<TaskTimelineDto>;
        message?: string;
    };
};

export type GetApiProjectsByProjectIdTasksByTaskIdTimelineResponse = GetApiProjectsByProjectIdTasksByTaskIdTimelineResponses[keyof GetApiProjectsByProjectIdTasksByTaskIdTimelineResponses];

export type PatchApiProjectsByProjectIdTasksBatchStatusData = {
    body: BatchStatusRequest;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/tasks/batch-status';
};

export type PatchApiProjectsByProjectIdTasksBatchStatusResponses = {
    /**
     * OK
     */
    200: {
        success: boolean;
        data: UpdatedCountDto;
        message?: string;
    };
};

export type PatchApiProjectsByProjectIdTasksBatchStatusResponse = PatchApiProjectsByProjectIdTasksBatchStatusResponses[keyof PatchApiProjectsByProjectIdTasksBatchStatusResponses];
