// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenStaff.Infrastructure.Persistence;

#nullable disable

namespace OpenStaff.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407064406_AddAgentRoleAvatar")]
    partial class AddAgentRoleAvatar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("OpenStaff.Core.Models.AgentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentEventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AgentEvents_CreatedAt");

                    b.HasIndex("ParentEventId");

                    b.HasIndex("AgentId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("ProjectId", "AgentId")
                        .HasDatabaseName("IX_AgentEvents_ProjectId_AgentId");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("agent_events", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.AgentRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModelProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PluginId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PluginId");

                    b.ToTable("agent_roles", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.AgentRoleMcpConfig", b =>
                {
                    b.Property<Guid>("AgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("McpServerConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolFilter")
                        .HasColumnType("text");

                    b.HasKey("AgentRoleId", "McpServerConfigId");

                    b.HasIndex("McpServerConfigId");

                    b.ToTable("AgentRoleMcpConfigs", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ChatFrame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitiatorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentFrameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRole")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentFrameId");

                    b.HasIndex("SessionId", "Depth");

                    b.ToTable("ChatFrames");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FrameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenUsage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FrameId", "SequenceNo");

                    b.HasIndex("SessionId", "SequenceNo");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextStrategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("full");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialInput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ChatSessions_CreatedAt");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("IX_ChatSessions_ProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ChatSessions_Status");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiffSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilesChanged")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskId");

                    b.ToTable("checkpoints", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.GlobalSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("global_settings", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.McpServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultConfig")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Homepage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketplaceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NpmPackage")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PypiPackage")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.HasIndex("Source");

                    b.ToTable("McpServers", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.McpServerConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthConfig")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionConfig")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentVariables")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("McpServerId");

                    b.ToTable("McpServerConfigs", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.Plugin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manifest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("plugins", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultModelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraConfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("zh-CN");

                    b.Property<Guid?>("MainSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("initializing");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Projects_CreatedAt");

                    b.HasIndex("MainSessionId")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Projects_Status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Projects_UpdatedAt");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ProjectAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentTask")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("idle");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentRoleId");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_agents", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ProviderAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvConfig")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EnvConfig");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("ProtocolType");

                    b.ToTable("ProviderAccounts", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.SessionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FrameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FrameId");

                    b.HasIndex("SessionId", "SequenceNo")
                        .IsUnique();

                    b.ToTable("SessionEvents");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.TaskDependency", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DependsOnId")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId", "DependsOnId");

                    b.HasIndex("DependsOnId");

                    b.ToTable("task_dependencies", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_TaskItems_Priority");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_TaskItems_ProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TaskItems_Status");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Core.Models.AgentEvent", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.ProjectAgent", "Agent")
                        .WithMany("Events")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Core.Models.AgentEvent", "ParentEvent")
                        .WithMany("ChildEvents")
                        .HasForeignKey("ParentEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenStaff.Core.Models.Project", "Project")
                        .WithMany("Events")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("ParentEvent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.AgentRole", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.Plugin", "Plugin")
                        .WithMany("AgentRoles")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("OpenStaff.Core.Models.AgentSoul", "Soul", b1 =>
                        {
                            b1.Property<Guid>("AgentRoleId");

                            b1.PrimitiveCollection<string>("Attitudes")
                                .IsRequired();

                            b1.Property<string>("Custom");

                            b1.Property<string>("Style");

                            b1.PrimitiveCollection<string>("Traits")
                                .IsRequired();

                            b1.HasKey("AgentRoleId");

                            b1.ToTable("agent_roles");

                            b1
                                .ToJson("Soul")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AgentRoleId");
                        });

                    b.Navigation("Plugin");

                    b.Navigation("Soul");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.AgentRoleMcpConfig", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.AgentRole", "AgentRole")
                        .WithMany()
                        .HasForeignKey("AgentRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Core.Models.McpServerConfig", "McpServerConfig")
                        .WithMany("AgentBindings")
                        .HasForeignKey("McpServerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRole");

                    b.Navigation("McpServerConfig");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ChatFrame", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.ChatFrame", "ParentFrame")
                        .WithMany("ChildFrames")
                        .HasForeignKey("ParentFrameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenStaff.Core.Models.ChatSession", "Session")
                        .WithMany("Frames")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentFrame");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ChatMessage", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.ChatFrame", "Frame")
                        .WithMany("Messages")
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Core.Models.ChatSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ChatSession", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.Checkpoint", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.ProjectAgent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Core.Models.Project", "Project")
                        .WithMany("Checkpoints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Core.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.McpServerConfig", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.McpServer", "McpServer")
                        .WithMany("Configs")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.Project", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.ChatSession", "MainSession")
                        .WithOne()
                        .HasForeignKey("OpenStaff.Core.Models.Project", "MainSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MainSession");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ProjectAgent", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.AgentRole", "AgentRole")
                        .WithMany("ProjectAgents")
                        .HasForeignKey("AgentRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenStaff.Core.Models.Project", "Project")
                        .WithMany("Agents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRole");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.SessionEvent", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.ChatFrame", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Core.Models.ChatSession", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.TaskDependency", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.TaskItem", "DependsOn")
                        .WithMany("Dependents")
                        .HasForeignKey("DependsOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Core.Models.TaskItem", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOn");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.TaskItem", b =>
                {
                    b.HasOne("OpenStaff.Core.Models.ProjectAgent", "AssignedAgent")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Core.Models.TaskItem", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenStaff.Core.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedAgent");

                    b.Navigation("ParentTask");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.AgentEvent", b =>
                {
                    b.Navigation("ChildEvents");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.AgentRole", b =>
                {
                    b.Navigation("ProjectAgents");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ChatFrame", b =>
                {
                    b.Navigation("ChildFrames");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ChatSession", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Frames");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.McpServer", b =>
                {
                    b.Navigation("Configs");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.McpServerConfig", b =>
                {
                    b.Navigation("AgentBindings");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.Plugin", b =>
                {
                    b.Navigation("AgentRoles");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.Project", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Checkpoints");

                    b.Navigation("Events");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.ProjectAgent", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("OpenStaff.Core.Models.TaskItem", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");

                    b.Navigation("SubTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
