// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenStaff.EntityFrameworkCore;

#nullable disable

namespace OpenStaff.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419104423_RefactorIdentityModelProjectAgentRoles")]
    partial class RefactorIdentityModelProjectAgentRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("OpenStaff.Entities.AgentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentEventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AgentEvents_CreatedAt");

                    b.HasIndex("ParentEventId");

                    b.HasIndex("ProjectAgentRoleId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("ProjectId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("ProjectId", "ProjectAgentRoleId")
                        .HasDatabaseName("IX_AgentEvents_ProjectId_ProjectAgentRoleId");

                    b.ToTable("agent_events", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.AgentRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModelProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PluginId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PluginId");

                    b.ToTable("agent_roles", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.AgentRoleMcpBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeParameters")
                        .HasColumnType("text");

                    b.Property<string>("ToolFilter")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("McpServerId");

                    b.HasIndex("AgentRoleId", "McpServerId")
                        .IsUnique();

                    b.ToTable("AgentRoleMcpBindings", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.AgentRoleMcpConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("McpServerConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolFilter")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("McpServerConfigId");

                    b.HasIndex("AgentRoleId", "McpServerConfigId")
                        .IsUnique();

                    b.ToTable("AgentRoleMcpConfigs", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.AgentRoleSkillBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillInstallKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("AgentRoleId", "SkillInstallKey")
                        .IsUnique();

                    b.ToTable("AgentRoleSkillBindings", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.ChatFrame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ExecutionPackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InitiatorAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InitiatorProjectAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentFrameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetProjectAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionPackageId");

                    b.HasIndex("InitiatorAgentRoleId");

                    b.HasIndex("InitiatorProjectAgentRoleId");

                    b.HasIndex("ParentFrameId");

                    b.HasIndex("TargetAgentRoleId");

                    b.HasIndex("TargetProjectAgentRoleId");

                    b.HasIndex("TaskId");

                    b.HasIndex("SessionId", "Depth");

                    b.ToTable("ChatFrames");
                });

            modelBuilder.Entity("OpenStaff.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ExecutionPackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FrameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginatingFrameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenUsage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentRoleId");

                    b.HasIndex("ExecutionPackageId");

                    b.HasIndex("OriginatingFrameId");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("ProjectAgentRoleId");

                    b.HasIndex("FrameId", "SequenceNo");

                    b.HasIndex("SessionId", "SequenceNo");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("OpenStaff.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextStrategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("full");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialInput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scene")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("ProjectBrainstorm");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ChatSessions_CreatedAt");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_ChatSessions_ProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ChatSessions_Status");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.HasIndex("ProjectId", "Scene", "CreatedAt");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("OpenStaff.Entities.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiffSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilesChanged")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAgentRoleId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskId");

                    b.ToTable("checkpoints", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.ExecutionPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryKind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InitiatorAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InitiatorProjectAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentExecutionPackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RetryOfExecutionPackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RootFrameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scene")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceFrameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetProjectAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentRoleId");

                    b.HasIndex("InitiatorAgentRoleId");

                    b.HasIndex("InitiatorProjectAgentRoleId");

                    b.HasIndex("ParentExecutionPackageId");

                    b.HasIndex("ProjectAgentRoleId");

                    b.HasIndex("RetryOfExecutionPackageId");

                    b.HasIndex("RootFrameId");

                    b.HasIndex("SourceFrameId");

                    b.HasIndex("TargetAgentRoleId");

                    b.HasIndex("TargetProjectAgentRoleId");

                    b.HasIndex("TaskId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.HasIndex("ProjectId", "EntryKind", "CreatedAt");

                    b.HasIndex("SessionId", "Status", "CreatedAt");

                    b.ToTable("ExecutionPackages");
                });

            modelBuilder.Entity("OpenStaff.Entities.GlobalSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("global_settings", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.InstalledSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallRootPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Installs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawMetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAgentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallKey")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("SourceKey");

                    b.HasIndex("Scope", "ProjectId");

                    b.HasIndex("Owner", "Repo", "SkillId");

                    b.ToTable("InstalledSkills", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.McpServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultConfig")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Homepage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallInfo")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketplaceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NpmPackage")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PypiPackage")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Mode");

                    b.HasIndex("Name");

                    b.HasIndex("Source");

                    b.ToTable("McpServers", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.McpServerConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthConfig")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionConfig")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentVariables")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("McpServerId");

                    b.ToTable("McpServerConfigs", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.Plugin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manifest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("plugins", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultModelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraConfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("zh-CN");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("brainstorming");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("initializing");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Projects_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Projects_Status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Projects_UpdatedAt");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.ProjectAgentRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentTask")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("idle");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentRoleId");

                    b.HasIndex("ProjectId", "AgentRoleId")
                        .IsUnique();

                    b.ToTable("project_agent_roles", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.ProjectAgentRoleMcpBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeParameters")
                        .HasColumnType("text");

                    b.Property<string>("ToolFilter")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("McpServerId");

                    b.HasIndex("ProjectAgentRoleId", "McpServerId")
                        .IsUnique();

                    b.ToTable("ProjectAgentRoleMcpBindings", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.ProjectAgentRoleSkillBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillInstallKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("ProjectAgentRoleId", "SkillInstallKey")
                        .IsUnique();

                    b.ToTable("ProjectAgentRoleSkillBindings", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.ProviderAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("ProtocolType");

                    b.ToTable("ProviderAccounts", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.SessionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExecutionPackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FrameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceEffectIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceFrameId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionPackageId");

                    b.HasIndex("FrameId");

                    b.HasIndex("MessageId");

                    b.HasIndex("SessionId", "SequenceNo")
                        .IsUnique();

                    b.ToTable("SessionEvents");
                });

            modelBuilder.Entity("OpenStaff.Entities.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DependsOnId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnId");

                    b.HasIndex("TaskId", "DependsOnId")
                        .IsUnique();

                    b.ToTable("task_dependencies", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.TaskExecutionLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionPackageId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceEffectIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionPackageId", "SourceEffectIndex");

                    b.HasIndex("TaskId", "CreatedAt");

                    b.ToTable("TaskExecutionLinks");
                });

            modelBuilder.Entity("OpenStaff.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedProjectAgentRoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedProjectAgentRoleId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_TaskItems_Priority");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_TaskItems_ProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TaskItems_Status");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("OpenStaff.Entities.AgentEvent", b =>
                {
                    b.HasOne("OpenStaff.Entities.AgentEvent", "ParentEvent")
                        .WithMany("ChildEvents")
                        .HasForeignKey("ParentEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenStaff.Entities.ProjectAgentRole", "ProjectAgentRole")
                        .WithMany("Events")
                        .HasForeignKey("ProjectAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.Project", "Project")
                        .WithMany("Events")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentEvent");

                    b.Navigation("Project");

                    b.Navigation("ProjectAgentRole");
                });

            modelBuilder.Entity("OpenStaff.Entities.AgentRole", b =>
                {
                    b.HasOne("OpenStaff.Entities.Plugin", "Plugin")
                        .WithMany("AgentRoles")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("OpenStaff.Entities.AgentSoul", "Soul", b1 =>
                        {
                            b1.Property<Guid>("AgentRoleId");

                            b1.PrimitiveCollection<string>("Attitudes")
                                .IsRequired();

                            b1.Property<string>("Custom");

                            b1.Property<string>("Style");

                            b1.PrimitiveCollection<string>("Traits")
                                .IsRequired();

                            b1.HasKey("AgentRoleId");

                            b1.ToTable("agent_roles");

                            b1
                                .ToJson("Soul")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AgentRoleId");
                        });

                    b.Navigation("Plugin");

                    b.Navigation("Soul");
                });

            modelBuilder.Entity("OpenStaff.Entities.AgentRoleMcpBinding", b =>
                {
                    b.HasOne("OpenStaff.Entities.AgentRole", "AgentRole")
                        .WithMany("McpBindings")
                        .HasForeignKey("AgentRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Entities.McpServer", "McpServer")
                        .WithMany("RoleBindings")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRole");

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("OpenStaff.Entities.AgentRoleMcpConfig", b =>
                {
                    b.HasOne("OpenStaff.Entities.AgentRole", "AgentRole")
                        .WithMany()
                        .HasForeignKey("AgentRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Entities.McpServerConfig", "McpServerConfig")
                        .WithMany("AgentBindings")
                        .HasForeignKey("McpServerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRole");

                    b.Navigation("McpServerConfig");
                });

            modelBuilder.Entity("OpenStaff.Entities.AgentRoleSkillBinding", b =>
                {
                    b.HasOne("OpenStaff.Entities.AgentRole", "AgentRole")
                        .WithMany("SkillBindings")
                        .HasForeignKey("AgentRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRole");
                });

            modelBuilder.Entity("OpenStaff.Entities.ChatFrame", b =>
                {
                    b.HasOne("OpenStaff.Entities.ExecutionPackage", "ExecutionPackage")
                        .WithMany("Frames")
                        .HasForeignKey("ExecutionPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.AgentRole", null)
                        .WithMany()
                        .HasForeignKey("InitiatorAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ProjectAgentRole", null)
                        .WithMany()
                        .HasForeignKey("InitiatorProjectAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ChatFrame", "ParentFrame")
                        .WithMany("ChildFrames")
                        .HasForeignKey("ParentFrameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenStaff.Entities.ChatSession", "Session")
                        .WithMany("Frames")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Entities.AgentRole", null)
                        .WithMany()
                        .HasForeignKey("TargetAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ProjectAgentRole", null)
                        .WithMany()
                        .HasForeignKey("TargetProjectAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.TaskItem", "Task")
                        .WithMany("Frames")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExecutionPackage");

                    b.Navigation("ParentFrame");

                    b.Navigation("Session");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OpenStaff.Entities.ChatMessage", b =>
                {
                    b.HasOne("OpenStaff.Entities.AgentRole", null)
                        .WithMany()
                        .HasForeignKey("AgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ExecutionPackage", "ExecutionPackage")
                        .WithMany("Messages")
                        .HasForeignKey("ExecutionPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ChatFrame", "Frame")
                        .WithMany("Messages")
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Entities.ChatFrame", "OriginatingFrame")
                        .WithMany()
                        .HasForeignKey("OriginatingFrameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ChatMessage", "ParentMessage")
                        .WithMany("ChildMessages")
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenStaff.Entities.ProjectAgentRole", null)
                        .WithMany()
                        .HasForeignKey("ProjectAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ChatSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionPackage");

                    b.Navigation("Frame");

                    b.Navigation("OriginatingFrame");

                    b.Navigation("ParentMessage");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OpenStaff.Entities.ChatSession", b =>
                {
                    b.HasOne("OpenStaff.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OpenStaff.Entities.Checkpoint", b =>
                {
                    b.HasOne("OpenStaff.Entities.ProjectAgentRole", "ProjectAgentRole")
                        .WithMany()
                        .HasForeignKey("ProjectAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.Project", "Project")
                        .WithMany("Checkpoints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("ProjectAgentRole");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OpenStaff.Entities.ExecutionPackage", b =>
                {
                    b.HasOne("OpenStaff.Entities.AgentRole", null)
                        .WithMany()
                        .HasForeignKey("AgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.AgentRole", null)
                        .WithMany()
                        .HasForeignKey("InitiatorAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ProjectAgentRole", null)
                        .WithMany()
                        .HasForeignKey("InitiatorProjectAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ExecutionPackage", "ParentExecutionPackage")
                        .WithMany("ChildExecutionPackages")
                        .HasForeignKey("ParentExecutionPackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenStaff.Entities.ProjectAgentRole", null)
                        .WithMany()
                        .HasForeignKey("ProjectAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ExecutionPackage", "RetryOfExecutionPackage")
                        .WithMany("RetryExecutionPackages")
                        .HasForeignKey("RetryOfExecutionPackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenStaff.Entities.ChatFrame", "RootFrame")
                        .WithMany()
                        .HasForeignKey("RootFrameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ChatSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Entities.ChatFrame", "SourceFrame")
                        .WithMany()
                        .HasForeignKey("SourceFrameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.AgentRole", null)
                        .WithMany()
                        .HasForeignKey("TargetAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ProjectAgentRole", null)
                        .WithMany()
                        .HasForeignKey("TargetProjectAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentExecutionPackage");

                    b.Navigation("RetryOfExecutionPackage");

                    b.Navigation("RootFrame");

                    b.Navigation("Session");

                    b.Navigation("SourceFrame");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OpenStaff.Entities.InstalledSkill", b =>
                {
                    b.HasOne("OpenStaff.Entities.Project", "Project")
                        .WithMany("InstalledSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OpenStaff.Entities.McpServerConfig", b =>
                {
                    b.HasOne("OpenStaff.Entities.McpServer", "McpServer")
                        .WithMany("Configs")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("OpenStaff.Entities.ProjectAgentRole", b =>
                {
                    b.HasOne("OpenStaff.Entities.AgentRole", "AgentRole")
                        .WithMany("ProjectAgentRoles")
                        .HasForeignKey("AgentRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenStaff.Entities.Project", "Project")
                        .WithMany("AgentRoles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRole");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OpenStaff.Entities.ProjectAgentRoleMcpBinding", b =>
                {
                    b.HasOne("OpenStaff.Entities.McpServer", "McpServer")
                        .WithMany("ProjectBindings")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Entities.ProjectAgentRole", "ProjectAgentRole")
                        .WithMany("McpBindings")
                        .HasForeignKey("ProjectAgentRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpServer");

                    b.Navigation("ProjectAgentRole");
                });

            modelBuilder.Entity("OpenStaff.Entities.ProjectAgentRoleSkillBinding", b =>
                {
                    b.HasOne("OpenStaff.Entities.ProjectAgentRole", "ProjectAgentRole")
                        .WithMany("SkillBindings")
                        .HasForeignKey("ProjectAgentRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectAgentRole");
                });

            modelBuilder.Entity("OpenStaff.Entities.SessionEvent", b =>
                {
                    b.HasOne("OpenStaff.Entities.ExecutionPackage", "ExecutionPackage")
                        .WithMany("Events")
                        .HasForeignKey("ExecutionPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ChatFrame", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ChatMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.ChatSession", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionPackage");

                    b.Navigation("Frame");

                    b.Navigation("Message");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OpenStaff.Entities.TaskDependency", b =>
                {
                    b.HasOne("OpenStaff.Entities.TaskItem", "DependsOn")
                        .WithMany("Dependents")
                        .HasForeignKey("DependsOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Entities.TaskItem", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOn");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OpenStaff.Entities.TaskExecutionLink", b =>
                {
                    b.HasOne("OpenStaff.Entities.ExecutionPackage", "ExecutionPackage")
                        .WithMany("TaskExecutionLinks")
                        .HasForeignKey("ExecutionPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenStaff.Entities.TaskItem", "Task")
                        .WithMany("ExecutionLinks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionPackage");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OpenStaff.Entities.TaskItem", b =>
                {
                    b.HasOne("OpenStaff.Entities.ProjectAgentRole", "AssignedProjectAgentRole")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedProjectAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenStaff.Entities.TaskItem", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenStaff.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedProjectAgentRole");

                    b.Navigation("ParentTask");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OpenStaff.Entities.AgentEvent", b =>
                {
                    b.Navigation("ChildEvents");
                });

            modelBuilder.Entity("OpenStaff.Entities.AgentRole", b =>
                {
                    b.Navigation("McpBindings");

                    b.Navigation("ProjectAgentRoles");

                    b.Navigation("SkillBindings");
                });

            modelBuilder.Entity("OpenStaff.Entities.ChatFrame", b =>
                {
                    b.Navigation("ChildFrames");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("OpenStaff.Entities.ChatMessage", b =>
                {
                    b.Navigation("ChildMessages");
                });

            modelBuilder.Entity("OpenStaff.Entities.ChatSession", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Frames");
                });

            modelBuilder.Entity("OpenStaff.Entities.ExecutionPackage", b =>
                {
                    b.Navigation("ChildExecutionPackages");

                    b.Navigation("Events");

                    b.Navigation("Frames");

                    b.Navigation("Messages");

                    b.Navigation("RetryExecutionPackages");

                    b.Navigation("TaskExecutionLinks");
                });

            modelBuilder.Entity("OpenStaff.Entities.McpServer", b =>
                {
                    b.Navigation("Configs");

                    b.Navigation("ProjectBindings");

                    b.Navigation("RoleBindings");
                });

            modelBuilder.Entity("OpenStaff.Entities.McpServerConfig", b =>
                {
                    b.Navigation("AgentBindings");
                });

            modelBuilder.Entity("OpenStaff.Entities.Plugin", b =>
                {
                    b.Navigation("AgentRoles");
                });

            modelBuilder.Entity("OpenStaff.Entities.Project", b =>
                {
                    b.Navigation("AgentRoles");

                    b.Navigation("Checkpoints");

                    b.Navigation("Events");

                    b.Navigation("InstalledSkills");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("OpenStaff.Entities.ProjectAgentRole", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Events");

                    b.Navigation("McpBindings");

                    b.Navigation("SkillBindings");
                });

            modelBuilder.Entity("OpenStaff.Entities.TaskItem", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");

                    b.Navigation("ExecutionLinks");

                    b.Navigation("Frames");

                    b.Navigation("SubTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
