using Microsoft.Extensions.AI;
namespace OpenStaff.Agent.Services;

/// <summary>
/// zh-CN: 描述应由智能体运行时执行的一条逻辑消息。
/// en: Describes a logical message that should be executed by the agent runtime.
/// </summary>
/// <param name="Scene">
/// zh-CN: 消息所属的运行场景。
/// en: The runtime scene that owns the message.
/// </param>
/// <param name="MessageContext">
/// zh-CN: 用于回连业务实体的上下文标识。
/// en: Context identifiers used to reconnect the message to application state.
/// </param>
/// <param name="InputRole">
/// zh-CN: 本次输入消息的聊天角色。
/// en: The chat role of the input message.
/// </param>
/// <param name="Input">
/// zh-CN: 要发送给智能体的文本内容。
/// en: The text content sent to the agent.
/// </param>
/// <param name="AgentRoleId">
/// zh-CN: 可选的显式角色标识。
/// en: The optional explicit role identifier.
/// </param>
/// <param name="OverrideJson">
/// zh-CN: 可选的运行时角色覆盖 JSON。
/// en: Optional runtime role override JSON.
/// </param>
/// <param name="MessageId">
/// zh-CN: 可选的逻辑消息标识；为空时由运行时生成。
/// en: Optional logical message identifier; generated by the runtime when omitted.
/// </param>
public readonly record struct CreateMessageRequest(
    MessageScene Scene,
    MessageContext MessageContext,
    ChatRole InputRole,
    string Input,
    Guid? AgentRoleId = null,
    Guid? TargetAgentRoleId=null,
    string? OverrideJson = null,
    Guid? MessageId = null);
